### ISSUE TITLE
CT200 XMPP Configuration Error

### ISSUE THREAD

**Issue by D0L05** [bosch-thermostat/home-assistant-bosch-custom-component#101]
**XMPP Configuration Error**

When attempting to add my thermostat to the integration I receive the error detailed bellow.

**Steps :**
 
1. Open Integrations Menu
2.  Select Bosch Thermostat Integration
3.  Select EasyControl
4.  Enter Controller Details
5.  Error is reported

**System Details**

- Core Version : core-2021.11.1
- Supervisor Version : supervisor-2021.10.8
- OS : Home Assistant OS 6.6
- Hardware : Raspberry Pi 4B

**Core Log :** 

```
2021-11-05 11:19:05 ERROR (MainThread) [custom_components.bosch.config_flow] Error connecting Bosch at <DEVICE_SERIAL_NUMBER> - 
2021-11-05 11:19:05 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 246, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 333, in _async_handle_step
    if result["type"] not in (
TypeError: 'NoneType' object is not subscriptable
```

**Comment by pszafer** [comment]
what firmware version do you have?

**Comment by D0L05** [comment]
The CT200 Firmware is 03.06.05

**Comment by webeling67** [comment]
Curiousity question: Did you set the password in the EasyControl App at Settings-Personal. This was the reason I couldn't get CT200 connected.

**Comment by D0L05** [comment]
@webeling67 I can confirm I have set the personal password within the easycontrol app.

**Comment by webeling67** [comment]
My CT200 is also showing problems in HA, although in an different area. I did a scan of my network via the  bosch_cli scan from a Linux environment. I was able to confirm a working code on Linux level against CT200 Firmware 03.06.05. Maybe you can check, if a separate Linux can read your CT200.  Guide can be found here: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Run-Bosch-Scan-from-Command-Line


My system details are equal to yours. 
    Core Version : core-2021.11.1
    Supervisor Version : supervisor-2021.10.8
    OS : Home Assistant OS 6.6
    Hardware : Raspberry Pi3

**Comment by webeling67** [comment]
Just for info: My EasyControl password had the special character $ and that was breaking the HA integration. Something similar on your side?

**Comment by pszafer** [comment]
@D0L05 do you have more logs? I think, that error you pasted is not invoked by bosch lib

**Comment by D0L05** [comment]
The only errors I see are within the Core log: 
`2021-11-10 12:06:04 ERROR (MainThread) [aioxmpp.node.PresenceManagedClient] main failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/node.py", line 837, in _on_main_done
    task.result()
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/node.py", line 997, in _main
    await self._main_impl()
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/node.py", line 952, in _main_impl
    tls_transport, xmlstream, features = await connect_xmlstream(
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/node.py", line 384, in connect_xmlstream
    options = list(await discover_connectors(
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/node.py", line 145, in discover_connectors
    starttls_srv_records = await network.lookup_srv(
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/network.py", line 331, in lookup_srv
    answer = await repeated_query(
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/network.py", line 300, in repeated_query
    raise TimeoutError()
TimeoutError
2021-11-10 12:06:04 ERROR (MainThread) [custom_components.bosch.config_flow] Error connecting Bosch at <DEVICE_SERIAL_NUMBER> - 
2021-11-10 12:06:04 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 246, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 333, in _async_handle_step
    if result["type"] not in (
TypeError: 'NoneType' object is not subscriptable
`

**Comment by pszafer** [comment]
If you want you can PM me on discord channel, provide your credentials (temporary) and I can check if I can connect to it.
From logs it looks like something is blocking connection to Bosch XMPP server over 5222/5269 ports.

**Comment by D0L05** [comment]
@pszafer I punched a rather large hole in my firewall and it has sprung to life. Can you tell me the specific ports/protocols that I need to allow through. The current rule is too insecure.

**Comment by pszafer** [comment]
I'm not sure, can you sniff traffic? I think ports 5222, 5269 are enough.

**Comment by D0L05** [comment]
it appears that on initial setup port 853 is used. This is not concerning as it means that the DNS connection is using TLS.

**Comment by pszafer** [comment]
So that's something on your network config, never seen connection on this port.

**Comment by webeling67** [comment]
@D0L05: Can you please comment the minimum ports you will end with for your installation? I'll update the guides accordingly to have the results documented for the future.

**Comment by D0L05** [comment]
@pszafer This is interesting, my network is not requiring dns over tls, this is the first device inside my network to try and use it.
 
@webeling67 the ports I needed to open to make Easy Control work are listed bellow, these include what I had already opened for the app/thermostat to work as expected prior to setting up home assistant: 
TCP : 522 - 5223
TCP : 5580
TCP: 853  - Only used by Home Assistant

**Comment by webeling67** [comment]
@D0L05: Can this ticket be closed?

**Comment by D0L05** [comment]
@webeling67 yeah, this is resolved.
