### ISSUE TITLE
Integration with CT200 randomly stopps working

### ISSUE THREAD

**Issue by lbossle** [bosch-thermostat/home-assistant-bosch-custom-component#125]
**Describe the bug**
Initial setup of my CT 200 works flawlessly. After some time the climate controls in Home Assistant don't update anymore. Furthermore you can't control the thermostats through Home Assistant anymore. 
After I reboot HA the following error is shown:

> Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/bosch/__init__.py", line 124, in async_setup_entry
    return await gateway_entry.async_init()
  File "/config/custom_components/bosch/__init__.py", line 206, in async_init
    if await self.async_init_bosch():
  File "/config/custom_components/bosch/__init__.py", line 253, in async_init_bosch
    await self.gateway.check_connection()
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/gateway/base.py", line 307, in check_connection
    await self.initialize()
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/gateway/base.py", line 70, in initialize
    await self._update_info(initial_db.get(GATEWAY))
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/gateway/easycontrol.py", line 79, in _update_info
    response = await self._connector.get(uri)
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/connectors/xmpp.py", line 94, in get
    data = await self._request(method=GET, path=path)
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/connectors/xmpp.py", line 122, in _request
    await self.start()
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/connectors/xmpp.py", line 113, in start
    self._xmppstream = await self._st.enter_async_context(
  File "/usr/local/lib/python3.9/contextlib.py", line 575, in enter_async_context
    result = await _cm_type.__aenter__(cm)
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/node.py", line 1652, in __aenter__
    await conn_future
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/node.py", line 837, in _on_main_done
    task.result()
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/node.py", line 997, in _main
    await self._main_impl()
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/node.py", line 952, in _main_impl
    tls_transport, xmlstream, features = await connect_xmlstream(
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/node.py", line 384, in connect_xmlstream
    options = list(await discover_connectors(
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/node.py", line 145, in discover_connectors
    starttls_srv_records = await network.lookup_srv(
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/network.py", line 331, in lookup_srv
    answer = await repeated_query(
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/network.py", line 300, in repeated_query
    raise TimeoutError()
TimeoutError

Only after I reboot the virtual machine HA is running on the integration works again. The Problem has now occured about 3 times in two weeks.

**To Reproduce**
1. Occurs randomly

**Expected behavior**
The integration shouldn't lose connection.

**Version**
  - HA version? 2021.12.8
  - HA Bosch component version? 0.16.9
  - Python Bosch HTTP client version? -

** Debug SCAN **
** IMPORTANT **
Doesn't run from UI while the above mentioned error is shown.
This is the debug scan after the restart of the virtual machine with everything working fine: [click](http://jsonblob.com/930120708110172160)

**Comment by pszafer** [comment]
It's problem with network connection, so it might be "everything" -> DNS issue, connection dropped or some services you have in use.

**Comment by lbossle** [comment]
Do you know any way to maybe narrow the issue down? Do the debug logs contain relevant information regarding this? Thanks for your help!

**Comment by pszafer** [comment]
- When it's not working check if you can manage thermostat from the Bosch app. But try to change temp or mode etc, because app sometimes caches states and people think it's working when it's just cache visible.
- ping CT200 if it's visible in your network
- telnet `xmpp.rrcng.ticx.boschtt.net` over 5222 port from machine in your network and HA machine.

**Comment by lbossle** [comment]
Alright, I will try all of those things once it stops working again. Thanks again.

**Comment by lbossle** [comment]
So I think I managed to narrow the issue down. When it stops working all the above mentioned things work but in the DNS logs of HA if found the following error messages:

> [ERROR] plugin/errors: 2 _xmpp-client._tcp.xmpp.rrcng.ticx.boschtt.net. SRV: read tcp 127.0.0.1:51138->127.0.0.1:5553: i/o timeout
> [INFO] 127.0.0.1:41139 - 45092 "NS IN . udp 17 false 512" NOERROR - 0 30.001573826s
> [ERROR] plugin/errors: 2 . NS: dial tcp 1.0.0.1:853: i/o timeout
> [INFO] 127.0.0.1:35787 - 53135 "NS IN . udp 17 false 512" NOERROR - 0 30.002325349s
> [ERROR] plugin/errors: 2 . NS: dial tcp 1.0.0.1:853: i/o timeout

Thererfore I think this more of a problem of using HA OS (see [HA OS DNS Setting - Configuration not respected?](https://community.home-assistant.io/t/ha-os-dns-setting-configuration-not-respected/356572)).
I'll close the issue as this has presumably nothing to do with the bosch integration. Thanks for your help.

**Comment by lbossle** [comment]
For anyone with the same problem I seemingly fixed this by not using SSL with HA directly but instead using the nginx proxy app.
