### ISSUE TITLE
error in parsing Notifications causes HC1 entities unavailable

### ISSUE THREAD

**Issue by pswid** [bosch-thermostat/home-assistant-bosch-custom-component#135]
v0.17.3 started working with Buderus WSW196iT, but HC1 entities were unavailable at all time. In debug log I saw only error related to Notifications, not HC1:

```
2022-02-01 11:02:29 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /notifications
2022-02-01 11:02:29 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/bosch/__init__.py", line 394, in thermostat_refresh
    await self.component_update(SENSOR, event_time)
  File "/config/custom_components/bosch/__init__.py", line 373, in component_update
    await entity.bosch_object.update()
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/helper.py", line 263, in update
    self.process_results(result, key)
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/sensors/notification.py", line 25, in process_results
    key_suffix = "" if idx == 0 else "_" + idx
TypeError: can only concatenate str (not "int") to str
```

After disabling `sensor.notifications` in HA, HC1 entities started working, so it seems to be a cause. 
As you may see in my bosh_scan.json #133, my heatpump currently reports two errors but integration shows only first of them. Is it a reason of error in HA? 
Would you modify the integration to display all reported errors, please? It would be also good to show date of each error (as attribute?)

```
"id": "/notifications",
            "type": "errorList",
            "recordable": 0,
            "writeable": 0,
            "values": [
                {
                    "cat": "N",
                    "act": "A",
                    "dcd": "H01",
                    "ccd": 5504,
                    "orig": "8",
                    "t": "2022-01-31T11:06:06",
                    "dlv": "8",
                    "fc": "16"
                },
                {
                    "cat": "N",
                    "act": "A",
                    "dcd": "A01",
                    "ccd": 5503,
                    "orig": "8",
                    "t": "2022-01-31T11:06:06",
                    "dlv": "4",
                    "fc": "16"
                }
            ]
```
![image](https://user-images.githubusercontent.com/78219494/151953247-8a95e841-a7f9-49f3-ab78-28f27760f424.png)

![image](https://user-images.githubusercontent.com/78219494/151953332-1559f788-3e6f-43a6-aae5-41c1ce670b24.png)

**Comment by pswid** [comment]
Is there any progress in work on this problem?

**Comment by SmilyHM** [comment]
Hi, same here - and that's am important thing, cause my GB192i got massive errors (since last maintenance and another maintenance appointment...)

FYI - the readings from FHEM --> "km200"-module (I deleted most/all readings, wich were generated by the module itself)
 --> and sorry - I'm not a native speaker ;-)

```
/dhwCircuits/dhw1/actualTemp
/dhwCircuits/dhw1/charge
/dhwCircuits/dhw1/chargeDuration
/dhwCircuits/dhw1/currentSetpoint
/dhwCircuits/dhw1/holidayMode/activated
/dhwCircuits/dhw1/operationMode
/dhwCircuits/dhw1/singleChargeSetpoint
/dhwCircuits/dhw1/status
/dhwCircuits/dhw1/switchPrograms/A/1-Mo
/dhwCircuits/dhw1/switchPrograms/A/2-Tu
/dhwCircuits/dhw1/switchPrograms/A/3-We
/dhwCircuits/dhw1/switchPrograms/A/4-Th
/dhwCircuits/dhw1/switchPrograms/A/5-Fr
/dhwCircuits/dhw1/switchPrograms/A/6-Sa
/dhwCircuits/dhw1/switchPrograms/A/7-Su
/dhwCircuits/dhw1/temperatureLevels/high
/dhwCircuits/dhw1/temperatureLevels/off
/dhwCircuits/dhw1/waterFlow
/dhwCircuits/dhw1/workingTime
/gateway/DateTime
/gateway/instAccess
/gateway/instWriteAccess
/gateway/logging/userAcceptance
/gateway/update/status
/gateway/uuid
/gateway/versionFirmware
/gateway/versionHardware
/heatSources/CHpumpModulation
/heatSources/ChimneySweeper
/heatSources/actualCHPower
/heatSources/actualDHWPower
/heatSources/actualModulation
/heatSources/actualPower
/heatSources/actualSupplyTemperature
/heatSources/applianceSupplyTemperature
/heatSources/burnerModulationSetpoint
/heatSources/burnerPowerSetpoint
/heatSources/chimneyTemperature
/heatSources/energyMonitoring/consumption
/heatSources/energyMonitoring/correctionFactor
/heatSources/energyMonitoring/maxTankLevel
/heatSources/energyMonitoring/minTankLevel
/heatSources/energyMonitoring/startDateTime
/heatSources/energyMonitoring/tankLevel
/heatSources/fanSpeed_setpoint
/heatSources/flameStatus
/heatSources/gasAirPressure
/heatSources/hs1/actualModulation
/heatSources/hs1/actualPower
/heatSources/hs1/flameStatus
/heatSources/hs1/info/01/Id
/heatSources/hs1/info/01/No
/heatSources/hs1/info/01/Tok
/heatSources/hs1/info/01/Ver
/heatSources/hs1/type
/heatSources/info/01/Id
/heatSources/info/01/No
/heatSources/info/01/Tok
/heatSources/info/01/Ver
/heatSources/nominalCHPower
/heatSources/nominalDHWPower
/heatSources/numberOfStarts
/heatSources/powerSetpoint
/heatSources/returnTemperature
/heatSources/supplyTemperatureSetpoint
/heatSources/systemPressure
/heatSources/workingTime/centralHeating
/heatSources/workingTime/secondBurner
/heatSources/workingTime/totalSystem
/heatingCircuits/hc1/activeSwitchProgram
/heatingCircuits/hc1/actualSupplyTemperature
/heatingCircuits/hc1/currentRoomSetpoint
/heatingCircuits/hc1/currentSuWiMode
/heatingCircuits/hc1/fastHeatupFactor
/heatingCircuits/hc1/holidayMode/activated
/heatingCircuits/hc1/operationMode
/heatingCircuits/hc1/pumpModulation
/heatingCircuits/hc1/roomtemperature
/heatingCircuits/hc1/status
/heatingCircuits/hc1/suWiSwitchMode
/heatingCircuits/hc1/suWiThreshold
/heatingCircuits/hc1/supplyTemperatureSetpoint
/heatingCircuits/hc1/switchProgramMode
/heatingCircuits/hc1/switchPrograms/A/1-Mo
/heatingCircuits/hc1/switchPrograms/A/2-Tu
/heatingCircuits/hc1/switchPrograms/A/3-We
/heatingCircuits/hc1/switchPrograms/A/4-Th
/heatingCircuits/hc1/switchPrograms/A/5-Fr
/heatingCircuits/hc1/switchPrograms/A/6-Sa
/heatingCircuits/hc1/switchPrograms/A/7-Su
/heatingCircuits/hc1/switchPrograms/B/1-Mo
/heatingCircuits/hc1/switchPrograms/B/2-Tu
/heatingCircuits/hc1/switchPrograms/B/3-We
/heatingCircuits/hc1/switchPrograms/B/4-Th
/heatingCircuits/hc1/switchPrograms/B/5-Fr
/heatingCircuits/hc1/switchPrograms/B/6-Sa
/heatingCircuits/hc1/switchPrograms/B/7-Su
/heatingCircuits/hc1/temperatureLevels/comfort2
/heatingCircuits/hc1/temperatureLevels/eco
/heatingCircuits/hc1/temporaryRoomSetpoint
```
**`/notifications/Error-01`**
**`/notifications/Error-02`**
```
/system/appliance/actualSupplyTemperature
/system/brand
/system/bus
/system/healthStatus
/system/holidayModes/hm1/dhwMode
/system/holidayModes/hm1/hcMode
/system/holidayModes/hm1/startStop
/system/holidayModes/hm2/dhwMode
/system/holidayModes/hm2/hcMode
/system/holidayModes/hm2/startStop
/system/holidayModes/hm3/dhwMode
/system/holidayModes/hm3/hcMode
/system/holidayModes/hm3/startStop
/system/holidayModes/hm4/dhwMode
/system/holidayModes/hm4/hcMode
/system/holidayModes/hm4/startStop
/system/holidayModes/hm5/dhwMode
/system/holidayModes/hm5/hcMode
/system/holidayModes/hm5/startStop
/system/info/01/Id
/system/info/01/No
/system/info/01/Tok
/system/info/01/Ver
/system/info/02/Id
/system/info/02/No
/system/info/02/Tok
/system/info/02/Ver
/system/info/03/Id
/system/info/03/No
/system/info/03/Tok
/system/info/03/Ver
/system/minOutdoorTemp
/system/sensors/temperatures/chimney
/system/sensors/temperatures/hotWater_t2
/system/sensors/temperatures/outdoor_t1
/system/sensors/temperatures/return
/system/sensors/temperatures/supply_t1
/system/sensors/temperatures/supply_t1_setpoint
/system/sensors/temperatures/switch
/system/systemType
```

Best regards
Sascha
