### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by rabacen** [bosch-thermostat/home-assistant-bosch-custom-component#152]
- Originally had Bosch Thermostat installed and working.
- Upgraded HA, integration stopped working.
- Removed Bosch Thermostat integration.
- Reinstalled via HACS
- Trying to add back into HA, I get the error:

This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.

- Logs show:

2022-03-15 09:15:18 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.bosch.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 572, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 589, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/bosch/__init__.py", line 9, in <module>
    from bosch_thermostat_client.const import (
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/__init__.py", line 10, in <module>
    from .gateway import gateway_chooser
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/gateway/__init__.py", line 1, in <module>
    from .ivt import IVTGateway
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/gateway/ivt.py", line 18, in <module>
    from bosch_thermostat_client.connectors import connector_ivt_chooser
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/connectors/__init__.py", line 2, in <module>
    from .ivt import IVTXMPPConnector
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/connectors/ivt.py", line 2, in <module>
    import aioxmpp
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/__init__.py", line 101, in <module>
    from .errors import (  # NOQA
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/errors.py", line 538, in <module>
    class UserError(Exception):
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/errors.py", line 559, in UserError
    DEFAULT_FORMATTER = i18n.LocalizingFormatter()
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/i18n.py", line 108, in __init__
    self.tzinfo = tzinfo if tzinfo is not None else tzlocal.get_localzone()
  File "/usr/local/lib/python3.9/site-packages/tzlocal/unix.py", line 203, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/lib/python3.9/site-packages/tzlocal/unix.py", line 161, in _get_localzone
    tzenv = utils._tz_from_env()
  File "/usr/local/lib/python3.9/site-packages/tzlocal/utils.py", line 122, in _tz_from_env
    raise ZoneInfoNotFoundError(
tzlocal.utils.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like %s. \nPlease use a timezone in the form of Continent/City'
2022-03-15 09:15:18 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration bosch: Exception importing custom_components.bosch.config_flow

Any idea what's causing it and how I can resolve?

Thanks

**Comment by cucko** [comment]
i'm facing the same problem. any progress on this issue?

**Comment by cucko** [comment]
Got it, i have wrong timezone set in my docker container. Netherlands/Amsterdam instead of Europe/Amsterdam. All works fine now.

**Comment by pszafer** [comment]
yes, XMPP needs to have proper timezone set up.
