### ISSUE TITLE
Not able to add a second CT 200 device | Couldn't find device model. Got product ID: None

### ISSUE THREAD

**Issue by christophgasser** [bosch-thermostat/home-assistant-bosch-custom-component#153]
I was able to add a first CT 200 with no problem. Working fine. We have 4 CT 200 more to add. When I try to add another CT 200 to HA, I get this error messages:

2022-03-15 15:07:16 ERROR (MainThread) [bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None
2022-03-15 15:07:16 ERROR (MainThread) [custom_components.bosch] Your device is unknown null
2022-03-15 15:07:16 ERROR (MainThread) [custom_components.bosch] Cannot connect to Bosch gateway, host 1013XXXXXX with UUID: None

I have replaced the host Id in that post with some X.

I already reduced the length of the password to 8 chars (read somwhere that this could cause problems). No success. The pw for the working CT 200 is longer than 8 chars by the way.

All CT 200 belong to the same Bosch account.

Any idea how to solve that?

**Comment by christophgasser** [comment]
I did also a raw scan on a Linux machine. THis is the result:

```
2022-03-15 16:14:36 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/uuid
2022-03-15 16:14:42 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /system/interfaces
2022-03-15 16:14:48 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/versionFirmware
2022-03-15 16:14:54 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/productID
2022-03-15 16:15:00 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/DateTime
2022-03-15 16:15:00 ERROR (MainThread) [bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None
Traceback (most recent call last):
  File "/root/bosch/venv/bin/bosch_cli", line 8, in <module>
    sys.exit(cli())
  File "/root/bosch/venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/root/bosch/venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/root/bosch/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/bosch/venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/bosch/venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/root/bosch/venv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/bosch/venv/lib/python3.8/site-packages/bosch_thermostat_client/bosch_cli.py", line 79, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/root/bosch/venv/lib/python3.8/site-packages/bosch_thermostat_client/bosch_cli.py", line 234, in scan
    connected = True if ignore_unknown else await gateway.check_connection()
  File "/root/bosch/venv/lib/python3.8/site-packages/bosch_thermostat_client/gateway/base.py", line 307, in check_connection
    await self.initialize()
  File "/root/bosch/venv/lib/python3.8/site-packages/bosch_thermostat_client/gateway/base.py", line 90, in initialize
    raise UnknownDevice("Your device is unknown %s" % json.dumps(self._device))
bosch_thermostat_client.exceptions.UnknownDevice: Your device is unknown null
```
The host is definitly correct. Checked it several times to make sure there is no typo.

BR
C

**Comment by pszafer** [comment]
What firmware version are on those devices?

**Comment by christophgasser** [comment]
For completeness: It was FW 03.02.00
