### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by smartins4** [bosch-thermostat/home-assistant-bosch-custom-component#174]
Guys first installation and I keep getting "Unknown error occurred".
Using Nefit Easy (CT100).

Nefit Easy Bosch Thermostat integration works.

Any advise where to start troubleshooting?

**Comment by smartins4** [comment]
2022-07-07 17:56:07 WARNING (MainThread) [aioxmpp.node.PresenceManagedClient] out of connection attempts
2022-07-07 17:56:07 ERROR (MainThread) [aioxmpp.node.PresenceManagedClient] main failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/node.py", line 837, in _on_main_done
    task.result()
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/node.py", line 996, in _main
    await self._main_impl()
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/node.py", line 951, in _main_impl
    tls_transport, xmlstream, features = await connect_xmlstream(
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/node.py", line 384, in connect_xmlstream
    options = list(await discover_connectors(
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/node.py", line 145, in discover_connectors
    starttls_srv_records = await network.lookup_srv(
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/network.py", line 331, in lookup_srv
    answer = await repeated_query(
  File "/usr/local/lib/python3.9/site-packages/aioxmpp/network.py", line 300, in repeated_query
    raise TimeoutError()
TimeoutError
2022-07-07 17:56:07 ERROR (MainThread) [custom_components.bosch.config_flow] Error connecting Bosch at 519913648 - 
2022-07-07 17:56:07 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 220, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 205, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 348, in _async_handle_step
    if result["type"] not in (
TypeError: 'NoneType' object is not subscriptable

**Comment by smartins4** [comment]
I have tried both. first Nefit and now Easycontrol. Same results (identical log)

**Comment by smartins4** [comment]
Well, I do use a VPN, but neither my Nefit easy nor my HAOS run through a VPN.
I do run pfSense+ with pfBlockerNG and snort installed.
Do you think it may have to do with that? Why?
Again, my ksya/ha-nefiteasy integration works (some disconnections occasionally and currently not working with 2022.7.0). The Nefit android app and HAOS work fine.
Thanks anyway for thinking with me.

**Comment by pszafer** [comment]
other people reported that wrong configuration of vpn made Bosch servers to ban vpn IPs. If you use Nefit easy, then you should use Nefit option in my intergation. Try without vpn and let me know

**Comment by smartins4** [comment]
not running through a VPN. i'll see if i can find some info in firewall logs.
thanks anyway.
