### ISSUE TITLE
Upgrade to 0.19.2 from 0.18.3 broke the integration with IVT Premiumline EQ that was working

### ISSUE THREAD

**Issue by larsdunemark** [bosch-thermostat/home-assistant-bosch-custom-component#210]
**Describe the bug**
I was using the version 0.18.3 with IVT Premiumline EQ and got all data from the gateway. After upgrading the integration failes to load.

**To Reproduce**
1. Upgrade to 0.19.2 in HACS
2. Restart HA
3. Check integration status

**Expected behavior**
Should load the integration and continue to report the collected data

**Version**
  - HA version: Home Assistant 2022.10.2
  - Supervisor 2022.10.0
  - HA Bosch component version: v0.19.2

** Debug SCAN **
** IMPORTANT **
Go to Developer tools in Home Assistant, choose Service tab and choose `bosch.debug_scan`
Download file to your computer and upload it somewhere eg. https://jsonblob.com/
Service is not available

**Additional context**
Log trace:
`
Error setting up entry iCom_low_CAN_v1 CAN for bosch

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/bosch/__init__.py", line 145, in async_setup_entry
    _init_status: bool = await gateway_entry.async_init()
  File "/config/custom_components/bosch/__init__.py", line 238, in async_init
    if await self.async_init_bosch():
  File "/config/custom_components/bosch/__init__.py", line 292, in async_init_bosch
    await self.gateway.check_connection()
  File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/gateway/base.py", line 323, in check_connection
    await self.initialize()
  File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/gateway/base.py", line 77, in initialize
    self._db = get_db_of_firmware(self._device[TYPE], self._firmware_version)
  File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/db/__init__.py", line 50, in get_db_of_firmware
    _db = open_json(filepath)
  File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/db/__init__.py", line 29, in open_json
    datastore = json.load(db_file)
  File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 167 column 9 (char 4822)
`

**Comment by pszafer** [comment]
Can you check v0.19.3?
