### ISSUE TITLE
New CT200 is not adding devices & entities

### ISSUE THREAD

**Issue by christophgasser** [bosch-thermostat/home-assistant-bosch-custom-component#234]
I have HA 2022.11.4 (current version) with most current component version (should be v0.19.4). I have currently 3 CT200 thermostats. Working fine. Tried to add a new one. It shows up. When opening it, it just has "1 device" instead of 6 devices like the others (pre-existing ones).

When checking the logs I see this warning:

This error originated from a custom integration.

```
Logger: custom_components.bosch
Source: custom_components/bosch/__init__.py:167
Integration: Bosch thermostat (documentation, issues)
First occurred: 5:24:30 PM (1 occurrences)
Last logged: 5:24:30 PM

Unloading Bosch module.
```

As well as a bunch of errors like this:

```
Logger: homeassistant.components.climate
Source: custom_components/bosch/bosch_entity.py:60
Integration: Climate (documentation, issues)
First occurred: 5:24:34 PM (1 occurrences)
Last logged: 5:24:34 PM

Error while setting up bosch platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bosch/climate.py", line 38, in async_setup_entry
    data[CLIMATE] = [
  File "/config/custom_components/bosch/climate.py", line 39, in <listcomp>
    BoschThermostat(
  File "/config/custom_components/bosch/climate.py", line 71, in __init__
    super().__init__(
  File "/config/custom_components/bosch/bosch_entity.py", line 60, in __init__
    self._unique_id = self._name + self._uuid
TypeError: can only concatenate str (not "NoneType") to str

```

Any idea how to fix that?

**Comment by christophgasser** [comment]
After several atempts it was working. DonÄ't know why.
