### ISSUE TITLE
CT200 Raw Scan result Successfully connected to gateway. Found UUID: None

### ISSUE THREAD

**Issue by EdwardVoermans** [bosch-thermostat/home-assistant-bosch-custom-component#251]
I'm hoping to add my Bosch CT200 Thermostat in Home Assistant.
As a first step I conducted to Raw Scan to verify if I can connect and retrieve the settings. 
The Raw Scan executes and lists a successful connection to the gateway but the resulting JSON file does not contain any information outside of "not found" for all entry's. 

To conduct the raw scan I followed the "Trace File of Communication with Bosch Device (Dev Raw Scan)" document. 
I have build a fresh Docker container Ubuntu 22.04.
Next steps:
- apt install software-properties-common
- add-apt-repository ppa:deadsnakes/ppa
- apt install python3.9 python3.9-venv
- apt install python3-pip
Followed by:
- cd ~
- mkdir bosch
- cd bosch
- python3.9 -m venv venv
- source venv/bin/activate
- pip3 install wheel
- pip3.9 install bosch-thermostat-client

Bosch CT200 Main Firmware version: 03.12.00
Bosch CT200 Hardware version: 10

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**
  - HA version? Not yet applicable
  - HA Bosch component version? CT200 firmware 03.12.00
  - Python Bosch HTTP client version? Latest version, installed today

** Debug SCAN **
** IMPORTANT **
Go to Developer tools in Home Assistant, choose Service tab and choose `bosch.debug_scan`
Download file to your computer and upload it somewhere eg. https://jsonblob.com/

**Additional context**
Result of "bosch_cli scan --host=101118168 --token=******** --password=******* --protocol=XMPP --device=EASYCONTROL"

`(venv) root@eecc4ea70ec1:/bosch# bosch_cli scan --host=101118168 --token=***** --password=**** --protocol=XMPP --device=EASYCONTROL
2023-01-06 16:05:20 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/uuid
2023-01-06 16:05:20 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /system/interfaces
2023-01-06 16:05:20 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/versionFirmware
2023-01-06 16:05:20 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/productID
2023-01-06 16:05:20 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/DateTime
2023-01-06 16:05:20 ERROR (MainThread) [bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None
Traceback (most recent call last):
  File "/bosch/venv/bin/bosch_cli", line 8, in <module>
    sys.exit(cli())
  File "/bosch/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/bosch/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/bosch/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/bosch/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/bosch/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/bosch/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/bosch/venv/lib/python3.9/site-packages/bosch_thermostat_client/bosch_cli.py", line 86, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/bosch/venv/lib/python3.9/site-packages/bosch_thermostat_client/bosch_cli.py", line 241, in scan
    connected = True if ignore_unknown else await gateway.check_connection()
  File "/bosch/venv/lib/python3.9/site-packages/bosch_thermostat_client/gateway/base.py", line 323, in check_connection
    await self.initialize()
  File "/bosch/venv/lib/python3.9/site-packages/bosch_thermostat_client/gateway/base.py", line 92, in initialize
    raise UnknownDevice("Your device is unknown %s" % json.dumps(self._device))
bosch_thermostat_client.exceptions.UnknownDevice: Your device is unknown null`

On Screen Result of "bosch_cli scan -i --host=101118168 --token=******** --password=******* --protocol=XMPP --device=EASYCONTROL"

`(venv) root@eecc4ea70ec1:/bosch# bosch_cli scan -i --host=101118168 --token=**** --password=***** --protocol=XMPP --device=EASYCONTROL
2023-01-06 16:13:31 INFO (MainThread) [bosch_thermostat_client.bosch_cli] Running scan
2023-01-06 16:13:31 INFO (MainThread) [bosch_thermostat_client.bosch_cli] Successfully connected to gateway. Found UUID: None
2023-01-06 16:13:31 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.1 404 Not Found', 'Seq-No: 0', 'Content-Length: 0', 'Content-Type: application/json', 'Connection: close', '', '']
2023-01-06 16:13:31 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /systemStates
2023-01-06 16:13:32 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /dhwCircuits
2023-01-06 16:13:32 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway
2023-01-06 16:13:32 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /heatingCircuits
2023-01-06 16:13:32 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /heatSources
2023-01-06 16:13:32 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /notifications
2023-01-06 16:13:32 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /system
2023-01-06 16:13:32 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /solarCircuits
2023-01-06 16:13:32 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.1 404 Not Found', 'Seq-No: 8', 'Content-Length: 0', 'Content-Type: application/json', 'Connection: close', '', '']
2023-01-06 16:13:32 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /recordings
2023-01-06 16:13:33 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /devices
2023-01-06 16:13:33 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /energy
2023-01-06 16:13:33 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /events
2023-01-06 16:13:33 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /programs
2023-01-06 16:13:33 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /zones
2023-01-06 16:13:33 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.1 404 Not Found', 'Seq-No: 14', 'Content-Length: 0', 'Content-Type: application/json', 'Connection: close', '', '']
2023-01-06 16:13:33 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /ecus
2023-01-06 16:13:33 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.1 404 Not Found', 'Seq-No: 15', 'Content-Length: 0', 'Content-Type: application/json', 'Connection: close', '', '']
2023-01-06 16:13:33 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /application
2023-01-06 16:13:33 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.1 404 Not Found', 'Seq-No: 16', 'Content-Length: 0', 'Content-Type: application/json', 'Connection: close', '', '']
2023-01-06 16:13:33 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gservice_tariff
2023-01-06 16:13:33 INFO (MainThread) [bosch_thermostat_client.bosch_cli] Successfully saved result to file: rawscan_None.json`

Content rawscan_None.json:

`(venv) root@eecc4ea70ec1:/bosch# cat rawscan_None.json
[
    {
        "/systemStates": "not found"
    },
    {
        "/dhwCircuits": "not found"
    },
    {
        "/gateway": "not found"
    },
    {
        "/heatingCircuits": "not found"
    },
    {
        "/heatSources": "not found"
    },
    {
        "/notifications": "not found"
    },
    {
        "/system": "not found"
    },
    {
        "/solarCircuits": "not found"
    },
    {
        "/recordings": "not found"
    },
    {
        "/devices": "not found"
    },
    {
        "/energy": "not found"
    },
    {
        "/events": "not found"
    },
    {
        "/programs": "not found"
    },
    {
        "/zones": "not found"
    },
    {
        "/ecus": "not found"
    },
    {
        "/application": "not found"
    },
    {
        "/gservice_tariff": "not found"
    }`
Thanks in advance for your assistance.

**Comment by Stijnele** [comment]
Hi, got a similar issue with a CT200. I'm not so experienced with debugging, but I got this as a result. I know that my password is longer than the advised 8 characters, but from the error I can not see that would cause the issue.
2023-01-14 06:51:08.209 INFO (MainThread) [custom_components.bosch] Setting up Bosch component version 0.20.0.
2023-01-14 06:51:08.209 DEBUG (MainThread) [custom_components.bosch] Initializing Bosch integration.
2023-01-14 06:51:08.212 DEBUG (MainThread) [custom_components.bosch] Checking connection to Bosch gateway as 101427230.
2023-01-14 06:51:09.124 ERROR (MainThread) [bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None
2023-01-14 06:51:09.127 ERROR (MainThread) [custom_components.bosch] Your device is unknown null

**Comment by Cityboy3** [comment]
Hi Edward,

I linked my Bosch thermostat with undermentioned guide. This works great.

https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Home-Assistant-Installation-Guide

Marc

**Comment by EdwardVoermans** [comment]
> Hi Stijn, aha thanks for the URL. Just tested and the developer API works for me too! 
So it might be related to the endpoint Pavel is using in his bosch_cli toolset. I'm going to put in some time tomorrow (Sunday) to see if changing the endpoint is changing it to work . . .

**Comment by Stijnele** [comment]
Changing the password from 20+ characters to only 8 did the trick after all. Everything is working now!

**Comment by EdwardVoermans** [comment]
> Changing the password from 20+ characters to only 8 did the trick after all. Everything is working now!

I wonder how you managed to do that? Using identity-myprofile.bosch.com requires a minimum length of 10 characters . . .

**Comment by Stijnele** [comment]
I did change it from the app on my phone. No specific restrictions encountered.

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: EdwardVoermans ***@***.***>
Verzonden: Monday, January 16, 2023 10:44:59 AM
Aan: bosch-thermostat/home-assistant-bosch-custom-component ***@***.***>
CC: StijnV ***@***.***>; Manual ***@***.***>
Onderwerp: Re: [bosch-thermostat/home-assistant-bosch-custom-component] CT200 Raw Scan result Successfully connected to gateway. Found UUID: None (Issue #251)


Changing the password from 20+ characters to only 8 did the trick after all. Everything is working now!

I wonder how you managed to do that? Using identity-myprofile.bosch.com requires a minimum length of 10 characters . . .

**Comment by EdwardVoermans** [comment]
> I did change it from the app on my phone. No specific restrictions encountered. 
Then I can only guess that Bosch changed their pwd policy overnight. Just tried the EasyControl app (v. 4.0.0) and getting the (new) requirements 0...9 AZ !$#% >10
I'm starting to feel like a dog chasing his own tail . . .

**Comment by Stijnele** [comment]
I use 4.0.0 already for one month and that was no issue. I’m running the app on iOS.

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: EdwardVoermans ***@***.***>
Verzonden: Monday, January 16, 2023 11:26:11 AM
Aan: bosch-thermostat/home-assistant-bosch-custom-component ***@***.***>
CC: StijnV ***@***.***>; Manual ***@***.***>
Onderwerp: Re: [bosch-thermostat/home-assistant-bosch-custom-component] CT200 Raw Scan result Successfully connected to gateway. Found UUID: None (Issue #251)


I did change it from the app on my phone. No specific restrictions encountered.
Then I can only guess that Bosch changed their pwd policy overnight. Just tried the EasyControl app (v. 4.0.0) and getting the (new) requirements 0...9 AZ !$#% >10
I'm starting to feel like a dog chasing his own tail . . .

**Comment by EdwardVoermans** [comment]
> I use 4.0.0 already for one month and that was no issue. I’m running the app on iOS. 
So am I. Is your Bosch account also already migrated to a SingleKey ID (https://www.bosch-digital.com/bosch-id/)?
My account is of the new type . . .
