### ISSUE TITLE
Error: Config flow could not be loaded: {"message":"Invalid handler specified"} 

### ISSUE THREAD

**Issue by Sab44** [bosch-thermostat/home-assistant-bosch-custom-component#277]
**Describe the bug**
When trying to set up the Integration, I get an error pop-up in HA stating
```
Error 
Config flow could not be loaded: {"message":"Invalid handler specified"} 
```

In the logs:
```
2023-03-28 15:59:57.983 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.bosch.config_flow
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/config/custom_components/bosch/__init__.py", line 12, in <module>
from bosch_thermostat_client.const import (
File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/__init__.py", line 10, in <module>
from .gateway import gateway_chooser
File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/gateway/__init__.py", line 1, in <module>
from .ivt import IVTGateway, IVTMBLanGateway
File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/gateway/ivt.py", line 6, in <module>
from bosch_thermostat_client.connectors import connector_ivt_chooser
File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/connectors/__init__.py", line 2, in <module>
from .ivt import IVTXMPPConnector
File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/connectors/ivt.py", line 2, in <module>
import aioxmpp
File "/usr/local/lib/python3.10/site-packages/aioxmpp/__init__.py", line 121, in <module>
from .security_layer import make as make_security_layer # NOQA: F401
File "/usr/local/lib/python3.10/site-packages/aioxmpp/security_layer.py", line 131, in <module>
import aiosasl
File "/usr/local/lib/python3.10/site-packages/aiosasl/__init__.py", line 150, in <module>
from .anonymous import ( # noqa:F401
File "/usr/local/lib/python3.10/site-packages/aiosasl/anonymous.py", line 28, in <module>
logger = logging.getLogger()
TypeError: get_logger() missing 1 required positional argument: 'name'
2023-03-28 15:59:57.994 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration bosch: Exception importing custom_components.bosch.config_flow
```

**To Reproduce**
1. Download custom integration via HACS
2. Restart HA
3. Go to Settings -> Integrations and add Bosch Thermostat integration
4. Pop-up with spinner will show but result in the error described above after a short while
Note: the error shows up before I can make any configuration choices.

**Expected behavior**
Integration can be set up properly.

**Version**
  - Home Assistant 2023.3.6 Supervisor 2023.03.2 Operating System 9.5 Frontend 20230309.1 - latest 
  - HA Bosch component version: tried with 0.21.0 and 0.22.0dev1
  - Python Bosch HTTP client version: N/A (not relevant here?)

** Debug SCAN **
Not possible due to failure to set up the integration.

**Additional context**
I've previously tried to set up the integration but failed due to me not knowing my EasyRemote password. Maybe some leftover stuff is interfering with trying to do another setup? Probably not, but just to note it here.

**Comment by Sab44** [comment]
Just noticed the logs above seems somewhat specific for 0.22.0dev1 so here's the log for 0.21.0
```
2023-03-28 16:31:54.648 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.bosch.config_flow
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/config/custom_components/bosch/__init__.py", line 12, in <module>
from bosch_thermostat_client.const import (
File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/__init__.py", line 10, in <module>
from .gateway import gateway_chooser
File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/gateway/__init__.py", line 1, in <module>
from .ivt import IVTGateway
File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/gateway/ivt.py", line 6, in <module>
from bosch_thermostat_client.connectors import connector_ivt_chooser
File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/connectors/__init__.py", line 2, in <module>
from .ivt import IVTXMPPConnector
File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/connectors/ivt.py", line 2, in <module>
import aioxmpp
File "/usr/local/lib/python3.10/site-packages/aioxmpp/__init__.py", line 121, in <module>
from .security_layer import make as make_security_layer # NOQA: F401
File "/usr/local/lib/python3.10/site-packages/aioxmpp/security_layer.py", line 131, in <module>
import aiosasl
File "/usr/local/lib/python3.10/site-packages/aiosasl/__init__.py", line 150, in <module>
from .anonymous import ( # noqa:F401
File "/usr/local/lib/python3.10/site-packages/aiosasl/anonymous.py", line 28, in <module>
logger = logging.getLogger()
TypeError: get_logger() missing 1 required positional argument: 'name'
2023-03-28 16:31:54.659 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration bosch: Exception importing custom_components.bosch.config_flow
```

**Comment by pszafer** [comment]
Can you try 0.22.x?

**Comment by Sab44** [comment]
Tried on 0.22.2, same issue unfortunately.

After further investigation it seems to happen to multiple people in various integrations so most likely I was mistaken thinking it is the bosch thermostat integration's fault. No one can provide any information on what circumstances are causing this issue or how to fix it though which is quite frustrating.

Further info:
https://community.home-assistant.io/t/error-adding-integration/485237/14
https://github.com/home-assistant/frontend/issues/14376

Feel free to close this PR then and thank you for coming back to me.

**Comment by verwo** [comment]
same issue

**Comment by pszafer** [comment]
What type of device do you try to configure? IVT, Nefit?

**Comment by Sab44** [comment]
The error pop-up appears before you can make any choices / configuration. I can see the "please wait" pop-up with the spinner but then immediately receive the error pop-up.

Again, not sure if this is relevant, but I've previously tried to set up an IVT device but unsuccessful since I didn't know my EasyRemote password. Since then I have reinstalled the integration & restarted HA multiple times.

**Comment by verwo** [comment]
Solved. 
It was a problem with the timezone. Somehow tzlocal past the wrong timezone, Belgium/Brussels instead of Europe/Brussels.
Changing /usr/local/lib/python3.10/site-packages/tzlocal/utils.py manually to the right timezone solved the problem for me.

**Comment by Sab44** [comment]
> Solved. It was a problem with the timezone. Somehow tzlocal past the wrong timezone, Belgium/Brussels instead of Europe/Brussels. Changing /usr/local/lib/python3.10/site-packages/tzlocal/utils.py manually to the right timezone solved the problem for me.

Thanks for coming back to this thread @verwo. I'm not quite following your solution unfortunately, could you give more details? Is it a problem in the integration or in HA?

For example, in my Homeassistant OS there's no python directory in /usr/local/lib/

Thanks!

**Comment by ArnoutVos** [comment]
Same error in frontend, but different error in the log.

I'm running Home Assistant Core on Raspbian 11 Bullseye, upgrade from 2022.11 to 2023.4.6. It runs in Python venv environment.
I've compiled **Python 3.11** from source and installed it with altinstall.

It [looks](https://stackoverflow.com/questions/75043093/python-compiler-says-im-adding-an-extra-argument-to-int-in-an-enum) [like](https://github.com/python/cpython/issues/102549) this a Python 3.11 problem.

```
Apr 27 08:19:18 raspberrypi hass[9570]: #033[31m2023-04-27 08:19:18.891 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.bosch.config_flow
Apr 27 08:19:18 raspberrypi hass[9570]: Traceback (most recent call last):
Apr 27 08:19:18 raspberrypi hass[9570]:   File "/usr/local/lib/python3.11/enum.py", line 260, in __set_name__
Apr 27 08:19:18 raspberrypi hass[9570]:     enum_member._value_ = enum_class._member_type_(*args)
Apr 27 08:19:18 raspberrypi hass[9570]:                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 27 08:19:18 raspberrypi hass[9570]:   File "/srv/homeassistant/lib/python3.11/site-packages/aioxmpp/xso/model.py", line 2923, in __init__
Apr 27 08:19:18 raspberrypi hass[9570]:     self.xso_class = self._create_class()
Apr 27 08:19:18 raspberrypi hass[9570]:                      ^^^^^^^^^^^^^^^^^^^^
Apr 27 08:19:18 raspberrypi hass[9570]:   File "/srv/homeassistant/lib/python3.11/site-packages/aioxmpp/xso/model.py", line 2933, in _create_class
Apr 27 08:19:18 raspberrypi hass[9570]:     self._create_name(),
Apr 27 08:19:18 raspberrypi hass[9570]:     ^^^^^^^^^^^^^^^^^^^
Apr 27 08:19:18 raspberrypi hass[9570]:   File "/srv/homeassistant/lib/python3.11/site-packages/aioxmpp/xso/model.py", line 2926, in _create_name
Apr 27 08:19:18 raspberrypi hass[9570]:     return "".join(map(str.title, self.name.split("_")))
Apr 27 08:19:18 raspberrypi hass[9570]:                                   ^^^^^^^^^
Apr 27 08:19:18 raspberrypi hass[9570]: AttributeError: 'XSOEnumMixin' object has no attribute 'name'
Apr 27 08:19:18 raspberrypi hass[9570]: The above exception was the direct cause of the following exception:
Apr 27 08:19:18 raspberrypi hass[9570]: Traceback (most recent call last):
Apr 27 08:19:18 raspberrypi hass[9570]:   File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 779, in get_platform
Apr 27 08:19:18 raspberrypi hass[9570]:     cache[full_name] = self._import_platform(platform_name)
Apr 27 08:19:18 raspberrypi hass[9570]:                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 27 08:19:18 raspberrypi hass[9570]:   File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 796, in _import_platform
Apr 27 08:19:18 raspberrypi hass[9570]:     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
Apr 27 08:19:18 raspberrypi hass[9570]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 27 08:19:18 raspberrypi hass[9570]:   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
Apr 27 08:19:18 raspberrypi hass[9570]:     return _bootstrap._gcd_import(name[level:], package, level)
Apr 27 08:19:18 raspberrypi hass[9570]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 27 08:19:18 raspberrypi hass[9570]:   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
Apr 27 08:19:18 raspberrypi hass[9570]:   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
Apr 27 08:19:18 raspberrypi hass[9570]:   File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
Apr 27 08:19:18 raspberrypi hass[9570]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
Apr 27 08:19:18 raspberrypi hass[9570]:   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
Apr 27 08:19:18 raspberrypi hass[9570]:   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
Apr 27 08:19:18 raspberrypi hass[9570]:   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
Apr 27 08:19:18 raspberrypi hass[9570]:   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
Apr 27 08:19:18 raspberrypi hass[9570]:   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
Apr 27 08:19:18 raspberrypi hass[9570]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
Apr 27 08:19:18 raspberrypi hass[9570]:   File "/home/homeassistant/.homeassistant/custom_components/bosch/__init__.py", line 29, in <module>
Apr 27 08:19:18 raspberrypi hass[9570]:     from bosch_thermostat_client.version import __version__ as LIBVERSION
Apr 27 08:19:18 raspberrypi hass[9570]:   File "/srv/homeassistant/lib/python3.11/site-packages/bosch_thermostat_client/__init__.py", line 10, in <module>
Apr 27 08:19:18 raspberrypi hass[9570]:     from .gateway import gateway_chooser
Apr 27 08:19:18 raspberrypi hass[9570]:   File "/srv/homeassistant/lib/python3.11/site-packages/bosch_thermostat_client/gateway/__init__.py", line 1, in <module>
Apr 27 08:19:18 raspberrypi hass[9570]:     from .ivt import IVTGateway, IVTMBLanGateway
Apr 27 08:19:18 raspberrypi hass[9570]:   File "/srv/homeassistant/lib/python3.11/site-packages/bosch_thermostat_client/gateway/ivt.py", line 6, in <module>
Apr 27 08:19:18 raspberrypi hass[9570]:     from bosch_thermostat_client.connectors import connector_ivt_chooser
Apr 27 08:19:18 raspberrypi hass[9570]:   File "/srv/homeassistant/lib/python3.11/site-packages/bosch_thermostat_client/connectors/__init__.py", line 2, in <module>
Apr 27 08:19:18 raspberrypi hass[9570]:     from .ivt import IVTXMPPConnector
Apr 27 08:19:18 raspberrypi hass[9570]:   File "/srv/homeassistant/lib/python3.11/site-packages/bosch_thermostat_client/connectors/ivt.py", line 2, in <module>
Apr 27 08:19:18 raspberrypi hass[9570]:     import aioxmpp
Apr 27 08:19:18 raspberrypi hass[9570]:   File "/srv/homeassistant/lib/python3.11/site-packages/aioxmpp/__init__.py", line 101, in <module>
Apr 27 08:19:18 raspberrypi hass[9570]:     from .errors import (  # NOQA
Apr 27 08:19:18 raspberrypi hass[9570]:   File "/srv/homeassistant/lib/python3.11/site-packages/aioxmpp/errors.py", line 109, in <module>
Apr 27 08:19:18 raspberrypi hass[9570]:     class ErrorCondition(structs.CompatibilityMixin, xso.XSOEnumMixin, enum.Enum):
Apr 27 08:19:18 raspberrypi hass[9570]:   File "/usr/local/lib/python3.11/enum.py", line 557, in __new__
Apr 27 08:19:18 raspberrypi hass[9570]:     raise exc
Apr 27 08:19:18 raspberrypi hass[9570]:   File "/usr/local/lib/python3.11/enum.py", line 266, in __set_name__
Apr 27 08:19:18 raspberrypi hass[9570]:     raise new_exc
Apr 27 08:19:18 raspberrypi hass[9570]: TypeError: _value_ not set in __new__, unable to create it#033[0m
Apr 27 08:19:18 raspberrypi hass[9570]: #033[31m2023-04-27 08:19:18.924 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration bosch: Exception importing custom_components.bosch.config_flow#033[0m

```

**Comment by EmCeBeh** [comment]
Hello, I am experiencing the same issue. Is there a fix ? I just downloaded Bosch via  HACS in the latest raspi04 HA image. Thanks!

**Comment by Chaoskeeper** [comment]
using HAOS on a Proxmox for Homeassistant won't let me access the root. So can't change the utils.py file :(

any other fix?

**Comment by pszafer** [comment]
HAOS now gets newer version of python, so problem shouldn't occur anymore.
