### ISSUE TITLE
Energy statistics don't work anymore with CT200

### ISSUE THREAD

**Issue by doudz** [bosch-thermostat/home-assistant-bosch-custom-component#298]
Since few versions, Energy statistics are not working.
The last data update was 21/03/2023

![image](https://user-images.githubusercontent.com/1262548/236306540-485d68af-907b-46ee-83e3-428228f241cb.png)

I tried to downgrade to 0.20.2 or 0.21.0 but it doesn't help.
I don't see any error message, it just not works

Could you help ?

**Comment by zbikmarc** [comment]
I can add some from my side (same case): I can clearly see in `bosch_scan.json` that values (daily) are updated in json itself. I know that for sure cause I queried scan couple of days ago and today and I have new readings, but what I believe are old ones, are same (so they were not lost, overwritten or not updated).

**Comment by pszafer** [comment]
can you try version v0.22.3dev1?
You'd need to enable `Use new statistic API` in integration option once again.

**Comment by mcervar** [comment]
Hi

Today I tried with v0.22.3dev1 and also enabled Use new statistic API without luck.
Tried completely removing all entities and repo from HACS. Same thing.

Here is my debug json 
[bosch_scan.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/12068687/bosch_scan.zip)

**Comment by doudz** [comment]
Same for me, it's still not working

I have enable some disabled sensors in "Energy sensors" but it doesn't change anything

![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/1262548/e4fcefd2-bf7f-47a5-9687-7d8b00027a83)

**Comment by pszafer** [comment]
Recheck v0.23.1 and let me know

**Comment by mcervar** [comment]
Hi

I checked with v0.23.1 and it behaves the same :(

**Comment by MG-Sky** [comment]
I hope this is related by when i try to run:

```
service: bosch.fetch_recordings_sensor_range
data:
  uuid: "1XXXXX"
  day: "2023-07-20"
  statistic_id: energy:ehwenergy_hot_waterexternal
```

in logs:
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 680, in handle_execute_script
    response = await script_obj.async_run(msg.get("variables"), context=context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1569, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 420, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 470, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 493, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/config/custom_components/bosch/services.py", line 95, in async_handle_recording_sensor_fetch_past
    await entity.insert_statistics_range(start_time=day)
  File "/config/custom_components/bosch/sensor/statistic_helper.py", line 139, in insert_statistics_range
    await self._upsert_past_statistics(start=start, stop=stop)
  File "/config/custom_components/bosch/sensor/energy.py", line 159, in _upsert_past_statistics
    _value = round(day_data[self._read_attr] / 24, 2)
                   ~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'eHW'`

**Comment by MG-Sky** [comment]
same issue here, no logs since update to newest version of this integration (also have ct200).

**Comment by zbikmarc** [comment]
Unfortunately no change in my case. I have my firmware upgraded and recent version of module with `Use new statistic API` enabled.
I really do wonder what changed and if this is even fixable on this component level.

**Comment by mcervar** [comment]
For me exactly the same :/
It should be fixable because if you run full debug scan you can see that gas usage for yesterday is fetched, so my guess is probably the issue is in handling or storing the data to HA

**Comment by CR6-SE** [comment]
Is there a Update for that Problem? My statistic is still broken since Mai.

**Comment by zbikmarc** [comment]
I think I got it. This document was very eye opening: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Move-from-0.17-to-0.18-with-new-statistics
Naming of sensors have changed and looks like there is problem with merging old and new data into one place (solution from mentioned document did not work for me). Previously I was using `sensor.ractualpower` or sth similar but now I have to use `recording.acutalpowerexternal`.

And I can see in logs that data is updated:
```
2023-09-01 22:23:47.667 DEBUG (MainThread) [custom_components.bosch.sensor.recording] Appending day to statistic table with id: recording:ractualpowerexternal. Date: 2023-09-01 19:00:00+02:00, state: 3.4, sum: 3357.899999999996.
2023-09-01 22:23:47.667 DEBUG (MainThread) [custom_components.bosch.sensor.recording] Appending day to statistic table with id: recording:ractualpowerexternal. Date: 2023-09-01 11:00:00+02:00, state: 1.7, sum: 3354.499999999996.
2023-09-01 22:23:47.667 DEBUG (MainThread) [custom_components.bosch.sensor.recording] Appending day to statistic table with id: recording:ractualpowerexternal. Date: 2023-09-01 10:00:00+02:00, state: 1.3, sum: 3352.799999999996.
2023-09-01 22:23:47.667 DEBUG (MainThread) [custom_components.bosch.sensor.recording] Appending day to statistic table with id: recording:ractualpowerexternal. Date: 2023-09-01 05:00:00+02:00, state: 3.8, sum: 3351.499999999996.


2023-09-01 22:23:47.537 DEBUG (MainThread) [custom_components.bosch.sensor.recording] Appending day to statistic table with id: recording:ractualdhwpowerexternal. Date: 2023-09-01 19:00:00+02:00, state: 3.4, sum: 3309.0999999999945.
2023-09-01 22:23:47.537 DEBUG (MainThread) [custom_components.bosch.sensor.recording] Appending day to statistic table with id: recording:ractualdhwpowerexternal. Date: 2023-09-01 11:00:00+02:00, state: 1.7, sum: 3305.6999999999944.
2023-09-01 22:23:47.537 DEBUG (MainThread) [custom_components.bosch.sensor.recording] Appending day to statistic table with id: recording:ractualdhwpowerexternal. Date: 2023-09-01 10:00:00+02:00, state: 1.2, sum: 3303.9999999999945.
2023-09-01 22:23:47.537 DEBUG (MainThread) [custom_components.bosch.sensor.recording] Appending day to statistic table with id: recording:ractualdhwpowerexternal. Date: 2023-09-01 05:00:00+02:00, state: 3.8, sum: 3302.7999999999947.
```

**Comment by mcervar** [comment]
Hi

I dont even get to that point :/

`2023-08-25 10:06:00.001 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Sending GET request to /energy/historyEntries by 140361809309520
2023-08-25 10:06:00.092 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Response to GET request /energy/historyEntries: {"id": "/energy/historyEntries", "type": "floatValue", "writeable": 0, "recordable": 0, "value": 722.0, "used": "true", "available": "true", "unitOfMeasure": "", "minValue": 0.0, "maxValue": 6400.0, "stepSize": 1.0}
2023-08-25 10:06:00.092 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Sending GET request to /energy/history?entry=720 by 140361809309520
2023-08-25 10:06:00.184 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Response to GET request /energy/history?entry=720: {"id": "/energy/history", "type": "energyRecordings", "writeable": 0, "recordable": 0, "used": "true", "available": "true", "value": [{"d": "23-08-2023", "T": 26.5, "gCh": 0.0, "gHw": 4.4}, {"d": "24-08-2023", "T": 27.3, "gCh": 0.0, "gHw": 0.0}]}
2023-08-25 10:06:00.184 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Sending GET request to /energy/history?entry=721 by 140361809309520
2023-08-25 10:06:00.283 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Response to GET request /energy/history?entry=721: {"id": "/energy/history", "type": "energyRecordings", "writeable": 0, "recordable": 0, "used": "true", "available": "true", "value": [{"d": "24-08-2023", "T": 27.3, "gCh": 0.0, "gHw": 0.0}]}
2023-08-25 10:06:00.284 DEBUG (MainThread) [custom_components.bosch] Updating component 1-hour Sensor by 140361792640848
2023-08-25 10:06:00.284 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Sending GET request to /energy/historyEntries by 140361809309520
2023-08-25 10:06:00.390 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Response to GET request /energy/historyEntries: {"id": "/energy/historyEntries", "type": "floatValue", "writeable": 0, "recordable": 0, "value": 722.0, "used": "true", "available": "true", "unitOfMeasure": "", "minValue": 0.0, "maxValue": 6400.0, "stepSize": 1.0}
2023-08-25 10:06:00.390 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Sending GET request to /energy/history?entry=720 by 140361809309520
2023-08-25 10:06:00.494 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Response to GET request /energy/history?entry=720: {"id": "/energy/history", "type": "energyRecordings", "writeable": 0, "recordable": 0, "used": "true", "available": "true", "value": [{"d": "23-08-2023", "T": 26.5, "gCh": 0.0, "gHw": 4.4}, {"d": "24-08-2023", "T": 27.3, "gCh": 0.0, "gHw": 0.0}]}
2023-08-25 10:06:00.495 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Sending GET request to /energy/history?entry=721 by 140361809309520
2023-08-25 10:06:00.582 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Response to GET request /energy/history?entry=721: {"id": "/energy/history", "type": "energyRecordings", "writeable": 0, "recordable": 0, "used": "true", "available": "true", "value": [{"d": "24-08-2023", "T": 27.3, "gCh": 0.0, "gHw": 0.0}]}
2023-08-25 10:06:00.582 DEBUG (MainThread) [custom_components.bosch] Next update of 1-hour sensors scheduled at: 2023-08-25 11:06:00+02:00
2023-08-25 10:06:00.582 DEBUG (MainThread) [custom_components.bosch] Bosch 1-hour entitites updated.
2023-08-25 10:06:00.582 DEBUG (MainThread) [custom_components.bosch.sensor.energy] Reading attribute not available eCH
2023-08-25 10:06:00.583 DEBUG (MainThread) [custom_components.bosch.sensor.energy] Reading attribute not available eHW`

**Comment by mcervar** [comment]
It seems it expect attributes in value eCH and eHW but real attributes in this values output are gCh and gHw?

**Comment by pszafer** [comment]
Please check out https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.23.3
I will reopen if problem'd still occur.

**Comment by doudz** [comment]
I confirm it works !! 🎉  thank you so much

**Comment by arny14** [comment]
It works fine ! Great job !

**Comment by CR6-SE** [comment]
Hey there, what have you done, to get ist working? Updatet top the new Version, but IT IS still Not working for me. 
Do I have to reinstall everything Clean? Since I have this Problem the Entities are doubled aswell. 

Best regards

**Comment by CR6-SE** [comment]
Okay got it.
You have to choose external2. It ist working. Thank you very much.
