### ISSUE TITLE
Bosch Easycontrol ct200 stopped working

### ISSUE THREAD

**Issue by incama** [bosch-thermostat/home-assistant-bosch-custom-component#299]
**Describe the bug**
Since a few weeks the integration stopped working. I already did a complete reinstall but the outcome is still the same.

**To Reproduce**
Follow the normal installation.

**Version**
Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1
Bosch Integration version v0.22.2

** Debug SCAN **
** IMPORTANT **
`2023-05-06 09:40:57.391 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Bosch CT200 for bosch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/bosch/__init__.py", line 147, in async_setup_entry
    _init_status: bool = await gateway_entry.async_init()
  File "/config/custom_components/bosch/__init__.py", line 240, in async_init
    if await self.async_init_bosch():
  File "/config/custom_components/bosch/__init__.py", line 311, in async_init_bosch
    supported_bosch = await self.gateway.get_capabilities()
  File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/gateway/base.py", line 240, in get_capabilities
    circuit_object = await self.initialize_circuits(circuit)
  File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/gateway/base.py", line 265, in initialize_circuits
    await self._data[circ_type].initialize(
  File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/circuits/circuits.py", line 93, in initialize
    circuit_object = self.create_circuit(circuit, database, current_date)
  File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/circuits/circuits.py", line 123, in create_circuit
    return EasyControlDVCircuit(
  File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/circuits/easycontrol/base.py", line 121, in __init__
    super().__init__(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/circuits/circuit.py", line 116, in __init__
    super().__init__(connector, attr_id, db, _type, bus_type)
  File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/circuits/circuit.py", line 54, in __init__
    self._sensors = Sensors(
  File "/usr/local/lib/python3.10/site-packages/bosch_thermostat_client/sensors/sensors.py", line 70, in __init__
    for sensor_id, sensor in sensors_db.items():
AttributeError: 'NoneType' object has no attribute 'items'`

Interesting fact is that the firmware of the Bosch easycontrol had been updated on the 24th of april 2023 to version 03.12.00. Maybe they introduced breaking changes.

**Comment by incama** [comment]
Reverted the integration back to v0.20.0 and it works once again.

**Comment by pszafer** [comment]
Fixed in 0.23.
