### ISSUE TITLE
cannot import name 'ClimateEntity' from homeassistant.components.climate

### ISSUE THREAD

**Issue by andreassolberg** [bosch-thermostat/home-assistant-bosch-custom-component#30]
Setting up Bosch Compress 7000i AW using IVT HTTP.
Latest HA version.

I installed this component from downloading the master branch? I see now that there is releases as well. I’ll test a release and see if the problem disappear.

I manually added the component through integrations. From what I can tell it only added one entity: `water_heater.dhw1`. and I get the following errors:

```
2020-05-01 09:27:01 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform bosch.climate: Platform not found (cannot import name 'ClimateEntity' from 'homeassistant.components.climate' (/usr/src/homeassistant/homeassistant/components/climate/__init__.py)).
2020-05-01 09:28:02 ERROR (MainThread) [homeassistant.helpers.entity] Update for water_heater.dhw1 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/bosch/water_heater.py", line 208, in update
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 443, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 297, in async_write_ha_state
    self._async_write_ha_state()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 314, in _async_write_ha_state
    attr = self.capability_attributes
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 153, in capability_attributes
    self.hass, self.min_temp, self.temperature_unit, self.precision
  File "/usr/src/homeassistant/homeassistant/helpers/temperature.py", line 26, in display_temp
    temperature = convert_temperature(temperature, temperature_unit, ha_unit)
  File "/usr/src/homeassistant/homeassistant/util/temperature.py", line 29, in convert
    raise ValueError(UNIT_NOT_RECOGNIZED_TEMPLATE.format(from_unit, TEMPERATURE))
ValueError: None is not a recognized temperature unit.
```

**Comment by pszafer** [comment]
I'd say that 0.7.2 version is pretty stable and master branch/0.8.x versions are testing. I added XMPP support and same time HA changes way of handling climate device...
Anyway I fixed issue of adding climate component.
For DHW I think I need bosch_scan of your setup as I cannot reproduce same bug.

**Comment by andreassolberg** [comment]
I downloaded the latest from master now, and your fix seem to have fixed this! Thanks a lot!
