### ISSUE TITLE
Config flow could not be loaded: {"message":"Invalid handler specified"}  on HA 2023.6.1

### ISSUE THREAD

**Issue by kodsama** [bosch-thermostat/home-assistant-bosch-custom-component#305]
**Describe the bug**
Upgrade of HomeAssistant broke the integration.

I get now the message: "Config flow could not be loaded: {"message":"Invalid handler specified"} " after Home Assistant upgraded to version 2023.6.1 (Frontend 20230608.0 - latest).

I tried the integration in master, v0.22.2 and v0.21.0 all gave the same result.

I get these log errors:
```
Logger: homeassistant.config_entries
Source: config_entries.py:863
First occurred: 22:09:22 (2 occurrences)
Last logged: 22:09:38

Error occurred loading flow for integration bosch: Exception importing custom_components.bosch.config_flow
```
```
This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/bosch/__init__.py:29
Integration: bosch (documentation, issues)
First occurred: 22:09:38 (1 occurrences)
Last logged: 22:09:38

Unexpected exception importing platform custom_components.bosch.config_flow
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/enum.py", line 260, in __set_name__
    enum_member._value_ = enum_class._member_type_(*args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioxmpp/xso/model.py", line 2923, in __init__
    self.xso_class = self._create_class()
                     ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioxmpp/xso/model.py", line 2933, in _create_class
    self._create_name(),
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioxmpp/xso/model.py", line 2926, in _create_name
    return "".join(map(str.title, self.name.split("_")))
                                  ^^^^^^^^^
AttributeError: 'XSOEnumMixin' object has no attribute 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/bosch/__init__.py", line 29, in <module>
    from bosch_thermostat_client.version import __version__ as LIBVERSION
  File "/usr/local/lib/python3.11/site-packages/bosch_thermostat_client/__init__.py", line 10, in <module>
    from .gateway import gateway_chooser
  File "/usr/local/lib/python3.11/site-packages/bosch_thermostat_client/gateway/__init__.py", line 1, in <module>
    from .ivt import IVTGateway, IVTMBLanGateway
  File "/usr/local/lib/python3.11/site-packages/bosch_thermostat_client/gateway/ivt.py", line 6, in <module>
    from bosch_thermostat_client.connectors import connector_ivt_chooser
  File "/usr/local/lib/python3.11/site-packages/bosch_thermostat_client/connectors/__init__.py", line 2, in <module>
    from .ivt import IVTXMPPConnector
  File "/usr/local/lib/python3.11/site-packages/bosch_thermostat_client/connectors/ivt.py", line 2, in <module>
    import aioxmpp
  File "/usr/local/lib/python3.11/site-packages/aioxmpp/__init__.py", line 101, in <module>
    from .errors import (  # NOQA
  File "/usr/local/lib/python3.11/site-packages/aioxmpp/errors.py", line 109, in <module>
    class ErrorCondition(structs.CompatibilityMixin, xso.XSOEnumMixin, enum.Enum):
  File "/usr/local/lib/python3.11/enum.py", line 557, in __new__
    raise exc
  File "/usr/local/lib/python3.11/enum.py", line 266, in __set_name__
    raise new_exc
TypeError: _value_ not set in __new__, unable to create it
```

**To Reproduce**
Upgrade home assistant to 2023.6.1

**Expected behavior**
The integration should load

**Screenshots**

**Version**
  - HA version? 2023.6.1
  - HA Bosch component version? master & 0.22.2
  - Python Bosch HTTP client version?

**Comment by kodsama** [comment]
FYI, this seems to be a duplicate of #304
