### ISSUE TITLE
Initialize throws error - Device null or unkown

### ISSUE THREAD

**Issue by chrisdevh** [bosch-thermostat/home-assistant-bosch-custom-component#332]
**Describe the bug**
The bug occured within the last three weeks. The component worked before. No change were did on the configuration of the component. A reinstall of the component and a setup with with IVT and HTML, did not help. The component throughs two errors. 

**Error 1**
Logger: bosch_thermostat_client.gateway.ivt
Source: custom_components/bosch/__init__.py:294
Integration: Bosch thermostat (documentation, issues)
First occurred: 08:55:53 (24 occurrences)
Last logged: 09:51:59

**Error 2**
Logger: custom_components.bosch
Source: custom_components/bosch/__init__.py:297
Integration: Bosch thermostat (documentation, issues)
First occurred: 08:55:53 (24 occurrences)
Last logged: 09:51:59
Your device is unknown null

**To Reproduce**
1. Install the component
2. Enter crendentials with IVT and HTML
3. Component will through error.

**Expected behavior**
Component will setup and through no error. 

**Version**
  - HA version:  Home Assistant 2023.10.1  --- Supervisor 2023.10.0 --- Operating System 10.5  --- Frontend 20231005.0 - latest 
  - HA Bosch component version:  v0.23.4
  - Python Bosch HTTP client version?

** Debug SCAN **
Could not be made, since the component could not be initialized.

Does anybody has an idea what the reason could be and how to solve it? Thank you in advance.

**Comment by JBakers** [comment]
same here

There are problems with config of your thermostat.
Your device is unknown null.
You can create issue on Github, but first
Go to [Developer Tools/Service](http://homeassistant.local:8123/developer-tools/service) and create bosch.debug_scan.
[BoschGithub](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component)

When I run the bosch.debug_scan: 
Kan service bosch.debug_scan niet aanroepen. required key not provided @ data['uuid']. Got None

**Comment by we5** [comment]
Same here too.

Interestingly i deactivated it some weeks ago and re-activated it last week or so. It worked again out of a sudden!

Yesterday I did a core update (from 2023.10.1 to 2023.10.3) and today I was greeted with the persistent notification again. I will restore to .1 and see if it works again.

**Comment by chrisdevh** [comment]
Reinstall, deactivating, activating, did not help yet. I can agree, with the newest version the error remains the same

 Home Assistant 2023.10.3 Supervisor 2023.10.0 Operating System 11.0 Frontend 20231005.0 - latest 

I woul like to make a debug scan, but since the device is not initialiszing, I assume I have no possibility for further logs. Anything I can do, to retrieve more logs for an analyse?

**Comment by lbbrhzn** [comment]
same here:

Message:
`There are problems with config of your thermostat.
Your device is unknown null.
You can create issue on Github, but first
Go to [Developer Tools/Service](https://home.lbbrhzn.nl:8443/developer-tools/service) and create bosch.debug_scan.
[BoschGithub](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component)
`

Log:
`2023-10-16 08:47:07.939 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/uuid
2023-10-16 08:47:14.288 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /system/interfaces
2023-10-16 08:47:22.919 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/versionFirmware
2023-10-16 08:47:29.029 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/productID
2023-10-16 08:47:30.560 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/DateTime
2023-10-16 08:47:30.560 ERROR (MainThread) [bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None`

**Comment by lbbrhzn** [comment]
The issue is probably related to the use of SingleKeyID:
See [bosch-xmpp](https://github.com/robertklep/bosch-xmpp/commit/4b2217acf779cfe614cc29c2c204bca33b4edaeb)

**Comment by chrisdevh** [comment]
@lbbrhzn: Thank you for the logs and referencing the other problem. I will try this and write back if it helped.

**Comment by chrisdevh** [comment]
Hi, unfortunatelly nothing helped. Here is what I tried. 

**Setup**
- I have a KM100 module connected via LAN to the heating. 
- The App that I need to use is from Buderus / Bosch and called "MyDevice" for Android. The EasyControl App did not work.
- A login with the single ID is not required. You log in with the login name, password that is printed on the device and a own username und password that you create yourself. 

**Observation**
- The App connected with the provided credentials perfectly. Thus, the credentials seem to be correct. 
- I tried to connect via IVT HTML and XAMP, no connection at all. The initialization got stuck. 

The interesing thing is, that this integration work until the beginning of the year very well. First the energy consumption was not working and regardless of the installed version could not be established agian, and from one day to another, the whole integration stop working. 

Maybe there is a problem with the connection from the integration to HA?

**Comment by Suvel01** [comment]
@lbbrhzn 
I can confirm that setting the Easycontroll password (even to the same as single Sign-on) fixed my issue.
I had had issues for months, but failed to have time to look into it.
Re-installation of HA and HACS integration did not fix the issue for me.

HA 2023.4 Frontend 20231005.0 - latest,  on Docker LXC via a PROXMOX setup.
HACS Bosch Thermostat version v 0.23.4.

Debug only via HA (i.e. could not create bosch.debug_scan):
[bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None
[bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None
[custom_components.bosch] Your device is unknown null
[homeassistant.config_entries] Config entry 'Unknown model' for bosch integration not ready yet: ('Cannot connect to Bosch gateway, host %s with UUID: %s', '1010_', None); Retrying in background
 [bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None
[custom_components.bosch] Your device is unknown null
etc. (continues)

**Comment by chrisdevh** [comment]
@Suvel01 Do you have a km100 and that works with the Easycontrol App?   Or have you just reset the password and got it back working?

**Comment by chrisdevh** [comment]
@lbbrhzn and @pszafer: After another complete uninstall via HACS, restart and reinstall with restart, I did get managed to connect the km100 via XMPP. The EasyControl App I am unable to connect to. With the "MyDevice" App from Bosch am able to connect. Interesting thing to note: The Android App has a button "local connection" which does not work either. IVT and HTTP still not work. 

Mybe it is a thing with only the local connection?

**Comment by chrisdevh** [comment]
Update - Even the energy dashboard is working again by activting "Use new API" and the values to track starting with r... Within the energy board you need to use the recordings starting with "stat". 

I am still unable to figure out why the local connection is not working.

**Comment by pszafer** [comment]
I don't know why it is not working for some people from time to time.
I'd need debug logs, are you able to install bosch cli on some other PC, so you can make scan from command line?

**Comment by chrisdevh** [comment]
@pszafer: Good idea. I will try this. In the meantime, since I got the it running via XMPP, I can also try, to add another "heating" via the local connection and than call the log service. Let me check the next days if this is working out.

**Comment by chrisdevh** [comment]
@pszafer : I have two updates. First what I got from the logger from home assistant. second what I got via the cli running docker. 

First log from activating the logger in home assistant. 

```
2023-10-23 22:01:16.138 ERROR (MainThread) [bosch_thermostat_client.gateway.ivt] I cannot find supported device. Your devices: null
2023-10-23 22:01:16.139 ERROR (MainThread) [custom_components.bosch] Your device is unknown null
2023-10-23 22:01:16.140 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Unknown model' for bosch integration not ready yet: ('Cannot connect to Bosch gateway, host %s with UUID: %s', 'IPCLEARD', None); Retrying in background
2023-10-23 22:01:16.275 INFO (MainThread) [custom_components.bosch] Setting up Bosch component version 0.23.2.
2023-10-23 22:01:16.275 DEBUG (MainThread) [custom_components.bosch] Initializing Bosch integration.
2023-10-23 22:01:16.275 DEBUG (MainThread) [custom_components.bosch] Checking connection to Bosch gateway as IPCLEARD.
2023-10-23 22:01:17.782 DEBUG (MainThread) [custom_components.bosch] Updating Bosch thermostat entitites.
2023-10-23 21:59:59.848 INFO (MainThread) [custom_components.bosch] Setting up Bosch component version 0.23.2.
2023-10-23 21:59:59.848 DEBUG (MainThread) [custom_components.bosch] Initializing Bosch integration.
2023-10-23 21:59:59.851 DEBUG (MainThread) [custom_components.bosch] Checking connection to Bosch gateway as IDCLEARED.
2023-10-23 21:59:59.853 INFO (MainThread) [custom_components.bosch] Setting up Bosch component version 0.23.2.
2023-10-23 21:59:59.853 DEBUG (MainThread) [custom_components.bosch] Initializing Bosch integration.
2023-10-23 21:59:59.854 DEBUG (MainThread) [custom_components.bosch] Checking connection to Bosch gateway as IPCLEARD.
```

Command for the CLI
```docker
docker run -it test scan -i --host=IP --token=TOKEN--password=PW--protocol XMPP --device IVT
```
IP, TOKEN and PW are replaced with my own data. 



And the log from the CLI
```
/usr/local/lib/python3.10/dist-packages/tzlocal/unix.py:193: UserWarning: Can not find any timezone configuration, defaulting to UTC.
  warnings.warn("Can not find any timezone configuration, defaulting to UTC.")
2023-10-24 20:27:20 INFO (MainThread) [__main__] Running scan
2023-10-24 20:27:20 INFO (MainThread) [__main__] Successfully connected to gateway. Found UUID: None
2023-10-24 20:27:21 ERROR (MainThread) [aioxmpp.node.PresenceManagedClient] main failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aioxmpp/node.py", line 837, in _on_main_done
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/aioxmpp/node.py", line 1005, in _main
    await self._main_impl()
  File "/usr/local/lib/python3.10/dist-packages/aioxmpp/node.py", line 951, in _main_impl
    tls_transport, xmlstream, features = await connect_xmlstream(
  File "/usr/local/lib/python3.10/dist-packages/aioxmpp/node.py", line 390, in connect_xmlstream
    result = await _try_options(
  File "/usr/local/lib/python3.10/dist-packages/aioxmpp/node.py", line 267, in _try_options
    features = await security_layer.negotiate_sasl(
  File "/usr/local/lib/python3.10/dist-packages/aioxmpp/security_layer.py", line 1179, in negotiate_sasl
    raise last_auth_error
  File "/usr/local/lib/python3.10/dist-packages/aioxmpp/security_layer.py", line 1162, in negotiate_sasl
    result = await sasl_provider.execute(
  File "/usr/local/lib/python3.10/dist-packages/aioxmpp/security_layer.py", line 962, in execute
    mechanism_worked = await self._execute(
  File "/usr/local/lib/python3.10/dist-packages/aioxmpp/security_layer.py", line 840, in _execute
    await mechanism.authenticate(sm, token)
  File "/usr/local/lib/python3.10/dist-packages/aiosasl/scram.py", line 158, in authenticate
    username, password = await self._credential_provider()
  File "/usr/local/lib/python3.10/dist-packages/aioxmpp/security_layer.py", line 938, in credential_provider
    raise aiosasl.AuthenticationFailure(
aiosasl.common.AuthenticationFailure: user intervention: authentication failed: authentication aborted by user
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/bosch_thermostat_client/bosch_cli.py", line 425, in <module>
    asyncio.get_event_loop().run_until_complete(cli())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bosch_thermostat_client/bosch_cli.py", line 103, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/bosch_thermostat_client/bosch_cli.py", line 271, in scan
    await _scan(gateway, smallscan, output, stdout)
  File "/usr/local/lib/python3.10/dist-packages/bosch_thermostat_client/bosch_cli.py", line 66, in _scan
    result = await gateway.rawscan()
  File "/usr/local/lib/python3.10/dist-packages/bosch_thermostat_client/gateway/base.py", line 296, in rawscan
    single_scan = await deep_into(root, [], self._connector.get)
  File "/usr/local/lib/python3.10/dist-packages/bosch_thermostat_client/helper.py", line 98, in deep_into
    resp = await get(url)
  File "/usr/local/lib/python3.10/dist-packages/bosch_thermostat_client/connectors/xmpp.py", line 94, in get
    data = await self._request(method=GET, path=path)
  File "/usr/local/lib/python3.10/dist-packages/bosch_thermostat_client/connectors/xmpp.py", line 124, in _request
    await self.start()
  File "/usr/local/lib/python3.10/dist-packages/bosch_thermostat_client/connectors/xmpp.py", line 113, in start
    self._xmppstream = await self._st.enter_async_context(
  File "/usr/lib/python3.10/contextlib.py", line 619, in enter_async_context
    result = await _cm_type.__aenter__(cm)
  File "/usr/local/lib/python3.10/dist-packages/aioxmpp/node.py", line 1660, in __aenter__
    await conn_future
  File "/usr/local/lib/python3.10/dist-packages/aioxmpp/node.py", line 837, in _on_main_done
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/aioxmpp/node.py", line 1005, in _main
    await self._main_impl()
  File "/usr/local/lib/python3.10/dist-packages/aioxmpp/node.py", line 951, in _main_impl
    tls_transport, xmlstream, features = await connect_xmlstream(
  File "/usr/local/lib/python3.10/dist-packages/aioxmpp/node.py", line 390, in connect_xmlstream
    result = await _try_options(
  File "/usr/local/lib/python3.10/dist-packages/aioxmpp/node.py", line 267, in _try_options
    features = await security_layer.negotiate_sasl(
  File "/usr/local/lib/python3.10/dist-packages/aioxmpp/security_layer.py", line 1179, in negotiate_sasl
    raise last_auth_error
  File "/usr/local/lib/python3.10/dist-packages/aioxmpp/security_layer.py", line 1162, in negotiate_sasl
    result = await sasl_provider.execute(
  File "/usr/local/lib/python3.10/dist-packages/aioxmpp/security_layer.py", line 962, in execute
    mechanism_worked = await self._execute(
  File "/usr/local/lib/python3.10/dist-packages/aioxmpp/security_layer.py", line 840, in _execute
    await mechanism.authenticate(sm, token)
  File "/usr/local/lib/python3.10/dist-packages/aiosasl/scram.py", line 158, in authenticate
    username, password = await self._credential_provider()
  File "/usr/local/lib/python3.10/dist-packages/aioxmpp/security_layer.py", line 938, in credential_provider
    raise aiosasl.AuthenticationFailure(
aiosasl.common.AuthenticationFailure: user intervention: authentication failed: authentication aborted by user
```

**Comment by chrisdevh** [comment]
Hi, I investigated further. Today I came one step further. Maybe somethin was wrong with the first query. 

```
docker run -it test query --host=IP --token=TOKEN --password=PASSWORD--protocol HTTP --device IVT -p "/gateway/uuid"
```

```
/usr/local/lib/python3.10/dist-packages/tzlocal/unix.py:193: UserWarning: Can not find any timezone configuration, defaulting to UTC.
  warnings.warn("Can not find any timezone configuration, defaulting to UTC.")
2023-10-25 18:46:22 INFO (MainThread) [__main__] Connecting to IP with 'HTTP'
2023-10-25 18:46:33 ERROR (MainThread) [bosch_thermostat_client.gateway.base] Connection timed out for /gateway/uuid.
2023-10-25 18:46:33 INFO (MainThread) [__main__] Query succeed: ('/gateway/uuid',)
[
    null
]
```

On the other side I was abel to connect via XMPP

```
docker run -it test query --host=ID--token=TOKEN--password=PASSWORD--protocol XMPP --device IVT -p "/gateway/uuid"
```

``` 
/usr/local/lib/python3.10/dist-packages/tzlocal/unix.py:193: UserWarning: Can not find any timezone configuration, defaulting to UTC.
  warnings.warn("Can not find any timezone configuration, defaulting to UTC.")
2023-10-25 18:45:50 INFO (MainThread) [__main__] Connecting to ID with 'XMPP'
2023-10-25 18:45:52 INFO (MainThread) [__main__] Query succeed: ('/gateway/uuid',)
[
    {
        "allowedValues": [
            "ID"
        ],
        "id": "/gateway/uuid",
        "recordable": 0,
        "type": "stringValue",
        "value": "ID",
        "writeable": 0
    }
]
```

TOKEN, ID, IP and PASSWORD are replaced with my personal credentials.

**Comment by chrisdevh** [comment]
Update: Two days ago the XMPP connection broke out of nowhere. Today, I investigated. Interestingly, I could not ping the heater, even if my network reported that it is connected. I unplugged the gateway from the heater, waited a couple of seconds and replugged it. Afterwards I was able to ping it again and the XMPP connection worked right away. Local connection sill no success.

**Comment by chrisdevh** [comment]
@pszafer: The problem still exists. Until now, I have no idea what the reason could be, why the integration, or the connection module to the heater start breaking from time to time. You might close this issue because we can not reproduce it yet for sure to identify the issue. I also opted for the esp ems hardware to test it.
