### ISSUE TITLE
get_activeswitchprogram error in logs

### ISSUE THREAD

**Issue by cpu601** [bosch-thermostat/home-assistant-bosch-custom-component#39]
**Describe the bug**
Every minute I see the following error in Home Assistant log:

````
2020-11-28 14:05:53 ERROR (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 404 Not Found', '', '', '']
2020-11-28 14:05:54 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/bosch/__init__.py", line 277, in thermostat_refresh
    await self.component_update(WATER_HEATER, event_time)
  File "/config/custom_components/bosch/__init__.py", line 254, in component_update
    await entity.bosch_object.update()
  File "/usr/local/lib/python3.8/site-packages/bosch_thermostat_client/circuits/circuit.py", line 242, in update
    active_program = self.get_activeswitchprogram()
  File "/usr/local/lib/python3.8/site-packages/bosch_thermostat_client/circuits/circuit.py", line 201, in get_activeswitchprogram
    return result["references"][0][ID].split("/")[-1]
KeyError: 'references'
````

Only the following integration entities are enabled:
- climate.hc1
- sensor.return_temp
- sensor.outdoor_temperature
- sensor.actual_supply_temp
- sensor.supply_temp_setpoint
- water_heater.dhw1

Rest is disabled.

**To Reproduce**
This happen without intervention every minute.

`activeSwitchProgram` looks ok in debug scan:

````
{
            "id": "/heatingCircuits/hc1/activeSwitchProgram",
            "type": "stringValue",
            "writeable": 1,
            "recordable": 0,
            "value": "A",
            "allowedValues": [
                "A",
                "B"
            ]
        }
````

**Version**
  - HA version: 0.118.4
  - HA Bosch component version: v0.9.3
  - Python Bosch HTTP client version? 04.07.03 ??

**Debug SCAN**
Debug scan attached.

While performing debug scan I also noted a bunch of errors appearing in the log:

````
2020-11-28 14:07:05 ERROR (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 403 Forbidden', '', '', '']
2020-11-28 14:07:05 ERROR (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 403 Forbidden', '', '', '']
2020-11-28 14:07:06 ERROR (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 403 Forbidden', '', '', '']
2020-11-28 14:07:07 ERROR (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 403 Forbidden', '', '', '']
2020-11-28 14:07:08 ERROR (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 403 Forbidden', '', '', '']
2020-11-28 14:07:08 ERROR (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 403 Forbidden', '', '', '']
2020-11-28 14:07:11 ERROR (MainThread) [bosch_thermostat_client.encryption.base_encryption] Unable to decrypt: b"m\xb4\xc2\x06\xd4(\xf0IX\x11\t<\xd0\xa5x\x0f\xd4\x80\xe0\xc7\n\x18\xb1\x1c\x80\xf2\x06\x80-\xeb\t\xb6\xaf\xb9\xf8\xc9\x97\x87|\xfeU\xc1\x1b5}\x9d\xba\x0b\xdc\xf0\xe7\xe4\x0c\x9a\x84\xd9\xf6\xb2~q\x16O-!\x0e\x15\xb2\xb6;\xb0\xcfA\x94\xf1\xc6\x83\xd7:\xb6\x95\xd1\x80bp\x86o\n\xdf\x82\xed\xe2\xb4GX\xcb\x1b\xbf\xd7`Q\xe1<\x88\xbf\xae\xbe2\xad\xa8\xfcX@\xda:\xe6\xd4\xdf\x0eD<aT\x99F\xf9y\xe2\r\xd17QA\xbd\xea'U\xa6\xa6\x08\xe0\x00\xf8\x14bHG\xcb\xf4G\xf4\xa7`\x1b\x9e\x04L\x8d\xc7|\xefr\x8c\xb2\x8b\xa0A\x9a\x8e\x1c\x9bF\x86\xaa\xf6\xac5A \x0b\x10]\xc78\x9e|\x93\xbb\x1e\xf1\xbb\xcf\xf9\xbc\xb2\x9e\x19\x1fl\x04\xb3U\xc9L\x87\x1a\xce\xf9\xcf'\xf8\xadIC\x1aaMn\x0e\x1d\x0b0\xa6\xd6\xac" with error: 'utf-8' codec can't decode byte 0xb4 in position 1: invalid start byte
2020-11-28 14:07:12 ERROR (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 403 Forbidden', '', '', '']
2020-11-28 14:07:14 ERROR (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 403 Forbidden', '', '', '']
2020-11-28 14:07:14 ERROR (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 403 Forbidden', '', '', '']
2020-11-28 14:07:15 ERROR (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 403 Forbidden', '', '', '']
2020-11-28 14:07:15 ERROR (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 403 Forbidden', '', '', '']
2020-11-28 14:07:16 ERROR (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 403 Forbidden', '', '', '']
2020-11-28 14:07:18 ERROR (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 403 Forbidden', '', '', '']
2020-11-28 14:07:19 ERROR (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 403 Forbidden', '', '', '']
2020-11-28 14:07:20 ERROR (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 403 Forbidden', '', '', '']
2020-11-28 14:07:20 ERROR (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 403 Forbidden', '', '', '']
````

[bosch_scan.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/5610642/bosch_scan.txt)

**Comment by pszafer** [comment]
I uploaded new version https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.9.4
Error should be less verbose but enable debug logging for component and we might find out what's wrong.
I added printing of the result which is retrieved from bosch.
https://github.com/bosch-thermostat/bosch-thermostat-client-python/blob/dev/bosch_thermostat_client/circuits/circuit.py#L199-L203

**Comment by cpu601** [comment]
Thanks for quick fix.
I installed the latest version and enabled debug log. I still see one error in the log every minute...

````
2020-11-28 14:52:43 INFO (MainThread) [custom_components.bosch] Setting up Bosch component version 0.9.4.
2020-11-28 14:52:43 DEBUG (MainThread) [custom_components.bosch] Checking connection to Bosch gateway as xxxx.
2020-11-28 14:52:53 DEBUG (MainThread) [custom_components.bosch] Bosch BUS detected: EMS
2020-11-28 14:52:56 INFO (MainThread) [custom_components.bosch] Bosch initialized.
2020-11-28 14:52:56 DEBUG (MainThread) [custom_components.bosch] Bosch component registered with platforms ['climate', 'water_heater', 'sensor'].
2020-11-28 14:52:56 DEBUG (SyncWorker_23) [custom_components.bosch] Registering service debug and service update interval.
2020-11-28 14:53:26 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsOutdoor temperature758351947 called.
2020-11-28 14:53:26 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsSupply temp setpoint758351947 called.
2020-11-28 14:53:26 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsActual supply temp758351947 called.
2020-11-28 14:53:26 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsReturn temp758351947 called.
2020-11-28 14:53:56 DEBUG (MainThread) [custom_components.bosch] Updating Bosch thermostat entitites.
2020-11-28 14:53:56 DEBUG (MainThread) [custom_components.bosch] Updating component sensor by 2926823000
2020-11-28 14:53:56 DEBUG (SyncWorker_19) [custom_components.bosch.climate] Update of climate hc1 component called.
2020-11-28 14:53:56 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsOutdoor temperature758351947 called.
2020-11-28 14:53:56 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsSupply temp setpoint758351947 called.
2020-11-28 14:53:56 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsActual supply temp758351947 called.
2020-11-28 14:53:56 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsReturn temp758351947 called.
2020-11-28 14:53:56 DEBUG (SyncWorker_10) [custom_components.bosch.water_heater] Updating Bosch water_heater.
2020-11-28 14:53:57 DEBUG (MainThread) [custom_components.bosch] Updating component sensor by 2926823000
2020-11-28 14:53:58 DEBUG (MainThread) [custom_components.bosch] Updating component sensor by 2926823000
2020-11-28 14:53:58 DEBUG (MainThread) [custom_components.bosch] Updating component sensor by 2926823000
2020-11-28 14:53:59 DEBUG (MainThread) [custom_components.bosch] Bosch sensor entitites updated.
2020-11-28 14:53:59 DEBUG (MainThread) [custom_components.bosch] Updating component climate by 2926823000
2020-11-28 14:53:59 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsOutdoor temperature758351947 called.
2020-11-28 14:53:59 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsSupply temp setpoint758351947 called.
2020-11-28 14:53:59 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsActual supply temp758351947 called.
2020-11-28 14:53:59 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsReturn temp758351947 called.
2020-11-28 14:54:03 DEBUG (MainThread) [custom_components.bosch] Bosch climate entitites updated.
2020-11-28 14:54:03 DEBUG (MainThread) [custom_components.bosch] Updating component water_heater by 2926823000
2020-11-28 14:54:03 DEBUG (SyncWorker_15) [custom_components.bosch.climate] Update of climate hc1 component called.
2020-11-28 14:54:07 ERROR (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 404 Not Found', '', '', '']
2020-11-28 14:54:08 DEBUG (MainThread) [custom_components.bosch] Bosch water_heater entitites updated.
2020-11-28 14:54:08 DEBUG (SyncWorker_7) [custom_components.bosch.water_heater] Updating Bosch water_heater.
2020-11-28 14:54:26 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsOutdoor temperature758351947 called.
2020-11-28 14:54:26 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsSupply temp setpoint758351947 called.
2020-11-28 14:54:26 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsActual supply temp758351947 called.
2020-11-28 14:54:26 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsReturn temp758351947 called.
2020-11-28 14:54:56 DEBUG (MainThread) [custom_components.bosch] Updating Bosch thermostat entitites.
2020-11-28 14:54:56 DEBUG (MainThread) [custom_components.bosch] Updating component sensor by 2926823000
2020-11-28 14:54:56 DEBUG (SyncWorker_16) [custom_components.bosch.climate] Update of climate hc1 component called.
2020-11-28 14:54:56 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsOutdoor temperature758351947 called.
2020-11-28 14:54:56 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsSupply temp setpoint758351947 called.
2020-11-28 14:54:56 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsActual supply temp758351947 called.
2020-11-28 14:54:56 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsReturn temp758351947 called.
2020-11-28 14:54:56 DEBUG (SyncWorker_16) [custom_components.bosch.water_heater] Updating Bosch water_heater.
2020-11-28 14:54:57 DEBUG (MainThread) [custom_components.bosch] Updating component sensor by 2926823000
2020-11-28 14:54:58 DEBUG (MainThread) [custom_components.bosch] Updating component sensor by 2926823000
2020-11-28 14:54:58 DEBUG (MainThread) [custom_components.bosch] Updating component sensor by 2926823000
2020-11-28 14:54:59 DEBUG (MainThread) [custom_components.bosch] Bosch sensor entitites updated.
2020-11-28 14:54:59 DEBUG (MainThread) [custom_components.bosch] Updating component climate by 2926823000
2020-11-28 14:54:59 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsOutdoor temperature758351947 called.
2020-11-28 14:54:59 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsSupply temp setpoint758351947 called.
2020-11-28 14:54:59 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsActual supply temp758351947 called.
2020-11-28 14:54:59 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsReturn temp758351947 called.
2020-11-28 14:55:02 DEBUG (MainThread) [custom_components.bosch] Bosch climate entitites updated.
2020-11-28 14:55:02 DEBUG (MainThread) [custom_components.bosch] Updating component water_heater by 2926823000
2020-11-28 14:55:02 DEBUG (SyncWorker_12) [custom_components.bosch.climate] Update of climate hc1 component called.
2020-11-28 14:55:06 ERROR (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 404 Not Found', '', '', '']
2020-11-28 14:55:07 DEBUG (MainThread) [custom_components.bosch] Bosch water_heater entitites updated.
2020-11-28 14:55:07 DEBUG (SyncWorker_2) [custom_components.bosch.water_heater] Updating Bosch water_heater.
2020-11-28 14:55:26 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsOutdoor temperature758351947 called.
2020-11-28 14:55:26 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsSupply temp setpoint758351947 called.
2020-11-28 14:55:26 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsActual supply temp758351947 called.
2020-11-28 14:55:26 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsReturn temp758351947 called.
2020-11-28 14:55:56 DEBUG (MainThread) [custom_components.bosch] Updating Bosch thermostat entitites.
2020-11-28 14:55:56 DEBUG (MainThread) [custom_components.bosch] Updating component sensor by 2926823000
2020-11-28 14:55:56 DEBUG (SyncWorker_4) [custom_components.bosch.climate] Update of climate hc1 component called.
2020-11-28 14:55:56 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsOutdoor temperature758351947 called.
2020-11-28 14:55:56 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsSupply temp setpoint758351947 called.
2020-11-28 14:55:56 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsActual supply temp758351947 called.
2020-11-28 14:55:56 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsReturn temp758351947 called.
2020-11-28 14:55:56 DEBUG (SyncWorker_19) [custom_components.bosch.water_heater] Updating Bosch water_heater.
2020-11-28 14:55:57 DEBUG (MainThread) [custom_components.bosch] Updating component sensor by 2926823000
2020-11-28 14:55:58 DEBUG (MainThread) [custom_components.bosch] Updating component sensor by 2926823000
2020-11-28 14:55:58 DEBUG (MainThread) [custom_components.bosch] Updating component sensor by 2926823000
2020-11-28 14:55:59 DEBUG (MainThread) [custom_components.bosch] Bosch sensor entitites updated.
2020-11-28 14:55:59 DEBUG (MainThread) [custom_components.bosch] Updating component climate by 2926823000
2020-11-28 14:55:59 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsOutdoor temperature758351947 called.
2020-11-28 14:55:59 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsSupply temp setpoint758351947 called.
2020-11-28 14:55:59 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsActual supply temp758351947 called.
2020-11-28 14:55:59 DEBUG (MainThread) [custom_components.bosch.sensor] Update of sensor SensorsReturn temp758351947 called.
2020-11-28 14:56:02 DEBUG (MainThread) [custom_components.bosch] Bosch climate entitites updated.
2020-11-28 14:56:02 DEBUG (MainThread) [custom_components.bosch] Updating component water_heater by 2926823000
2020-11-28 14:56:02 DEBUG (SyncWorker_20) [custom_components.bosch.climate] Update of climate hc1 component called.
2020-11-28 14:56:06 ERROR (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 404 Not Found', '', '', '']
````

Let me know if I can provide additional information or test something.
