### ISSUE TITLE
Can't install Bosch-Thermostat

### ISSUE THREAD

**Issue by chodenthalgithub** [bosch-thermostat/home-assistant-bosch-custom-component#395]
Hi, I can't install the Plugin. 
My Setup: 
Hass with docker on Arabian 23.11. 
Installed Repository over HACS. 
If I want to install the integration I get a: 
Error
Config flow could not be loaded: {"message":"Invalid handler specified"}. 
So the integration cannot be installed. 

I get the following logs in HASS: 
`Logger: homeassistant.loader
Source: loader.py:847
First occurred: 8:46:30 AM (2 occurrences)
Last logged: 8:53:28 AM

Unexpected exception importing platform custom_components.bosch.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 847, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 864, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/bosch/__init__.py", line 12, in <module>
    from bosch_thermostat_client.const import (
  File "/usr/local/lib/python3.12/site-packages/bosch_thermostat_client/__init__.py", line 10, in <module>
    from .gateway import gateway_chooser
  File "/usr/local/lib/python3.12/site-packages/bosch_thermostat_client/gateway/__init__.py", line 1, in <module>
    from .ivt import IVTGateway, IVTMBLanGateway
  File "/usr/local/lib/python3.12/site-packages/bosch_thermostat_client/gateway/ivt.py", line 6, in <module>
    from bosch_thermostat_client.connectors import connector_ivt_chooser
  File "/usr/local/lib/python3.12/site-packages/bosch_thermostat_client/connectors/__init__.py", line 2, in <module>
    from .ivt import IVTXMPPConnector
  File "/usr/local/lib/python3.12/site-packages/bosch_thermostat_client/connectors/ivt.py", line 2, in <module>
    import aioxmpp
  File "/usr/local/lib/python3.12/site-packages/aioxmpp/__init__.py", line 101, in <module>
    from .errors import (  # NOQA
  File "/usr/local/lib/python3.12/site-packages/aioxmpp/errors.py", line 538, in <module>
    class UserError(Exception):
  File "/usr/local/lib/python3.12/site-packages/aioxmpp/errors.py", line 559, in UserError
    DEFAULT_FORMATTER = i18n.LocalizingFormatter()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aioxmpp/i18n.py", line 108, in __init__
    self.tzinfo = tzinfo if tzinfo is not None else tzlocal.get_localzone()
                                                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tzlocal/unix.py", line 219, in get_localzone
    _cache_tz = _get_localzone()
                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tzlocal/unix.py", line 176, in _get_localzone
    tzenv = utils._tz_from_env()
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tzlocal/utils.py", line 109, in _tz_from_env
    raise zoneinfo.ZoneInfoNotFoundError(
zoneinfo._common.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like MY_TIME_ZONE. \nPlease use a timezone in the form of Continent/City'
`

and: 

`Logger: homeassistant.config_entries
Source: config_entries.py:2275
First occurred: 8:46:30 AM (2 occurrences)
Last logged: 8:53:28 AM

Error occurred loading flow for integration bosch: Exception importing custom_components.bosch.config_flow`

HASS Version is: 
Core
2024.2.4
Frontend
20240207.1

Python 3.12.1 (main, Jan  4 2024, 12:00:29) [GCC 13.2.1 20231014] on linux

Is there anything I can do? 

Regards
Christian

**Comment by sysdump** [comment]
From the beginning if the readme:
It will only work with at least Home Assistant 2023.7 and **maximum 2024.1** and Python >=3.11. It won't work with Home Assistant 2024.2 installed on HAOS which delivers Python 3.12.

**Comment by annotationshacker** [comment]
May I ask, is there a timelime for support of HA 2024.2 ?

**Comment by pszafer** [comment]
Don't know yet... https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues/390#issuecomment-1965056042
