### ISSUE TITLE
xmpp intergration errors after internet reconnect

### ISSUE THREAD

**Issue by cpu601** [bosch-thermostat/home-assistant-bosch-custom-component#40]
**Describe the bug**
After internet reconnection the following logs appear every minute in home assistant and sensors do not get updated anymore.

````
2020-11-29 07:55:12 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/bosch/__init__.py", line 275, in thermostat_refresh
    await self.component_update(SENSOR, event_time)
  File "/config/custom_components/bosch/__init__.py", line 254, in component_update
    await entity.bosch_object.update()
  File "/usr/local/lib/python3.8/site-packages/bosch_thermostat_client/helper.py", line 199, in update
    result = await self._connector.get(item[URI])
  File "/usr/local/lib/python3.8/site-packages/bosch_thermostat_client/connectors/xmpp.py", line 99, in get
    self.register_callbacks()
  File "/usr/local/lib/python3.8/site-packages/bosch_thermostat_client/connectors/xmpp.py", line 50, in register_callbacks
    self.message_dispatcher.register_callback(
  File "/usr/local/lib/python3.8/site-packages/aioxmpp/dispatcher.py", line 207, in register_callback
    raise ValueError(
ValueError: only one listener allowed per matcher
````

**To Reproduce**
1. Use xmpp integration
2. Reset internet connectivity

**Expected behavior**
Internet reconnect should not affect behavior of component.

**Version**
  - HA version: 0.118.4
  - HA Bosch component version: v0.9.4
  - Python Bosch HTTP client version?

**Debug SCAN**
Debug scan service is not starting with same error message: `only one listener allowed per matcher`

**Comment by pszafer** [comment]
I don't know how to fix this issue with aioxmpp.
I'm trying to rewrite this part with slixmpp, maybe it will give me an option to reconnect.

**Comment by pszafer** [comment]
Fixed in release 0.10.0
