### ISSUE TITLE
Integration stops working after few hours

### ISSUE THREAD

**Issue by mcervar** [bosch-thermostat/home-assistant-bosch-custom-component#404]
First of all, this new version is way faster when updating thermostats, really good job! For some reason after > 6h, integration simply stops working, everything becomes unavailable, if I restart the integration it again works perfectly for few hours and then same problem occurs. Tried completely uninstalling integration and repo, and then reinstalling it from scratch, didnt help.

![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/47822784/ff177d99-6f56-4ed9-9248-3eb345fa2c5e)

Bosch component version is v0.25.1

Debug SCAN  doesnt provided anything, it only say nothing is available (more information can be seen in debug logs attached)

[bosch_HA_debug_log.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/15106372/bosch_HA_debug_log.txt)

Everything works in this log output until around ~ 01:01:00, after that time in this example, most of the requests are getting null response, but the wierd thing is that some request got proper reply like current temperatures of the thermostats.

**Comment by Pommes2910** [comment]
same here

**Comment by pszafer** [comment]
Disable most sensor and leave only one climate entity enabled. Might be too many requests to bosch servers and you got locked temporarily.

**Comment by mcervar** [comment]
khmm, but if they lock me out, then it shouldn't work immediately if I restart the integration. From the sensors I only use battery status for each thermostat which is really important to me, this shouldnt be a problem.

Even from the logs its visible after the problem occurs, some of the requests like current temperature and set temperature is succesfully fetched, but device or entity becomes unavailable for some reason

**Comment by pszafer** [comment]
Do it just for testing so we could try to find out why there is no response from server.

**Comment by mcervar** [comment]
Found what the problem is in the logs today, integration (homeconnect sub lib, sseclient file ) implements oauth for auth towards bosch cloud api, token after X hours expires which causes communication to stop working.

I suggest using refresh token if possible, and if refresh token is to be expired, then new refresh token should be also requested.  It would be good to have try catch exceptions on all api calls towards bosch cloud or at least on important functions (not crucial but long term good to have) if not already implemented. :D

`Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeconnect/sseclient.py", line 81, in __next__
    next_chunk = next(self.resp_iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeconnect/api.py", line 168, in _listen
    for event in sse:
  File "/usr/local/lib/python3.12/site-packages/homeconnect/sseclient.py", line 91, in __next__
    self._connect()
  File "/usr/local/lib/python3.12/site-packages/homeconnect/sseclient.py", line 56, in _connect
    self.resp = requester.get(self.url, stream=True, **self.requests_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests_oauthlib/oauth2_session.py", line 483, in request
    url, headers, data = self._client.add_token(
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 217, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) `

[home-assistant_2024-04-27T19-07-06.159Z.log](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/15139592/home-assistant_2024-04-27T19-07-06.159Z.log)

**Comment by pszafer** [comment]
You talking about different integration. It's not homeconnect integration .

**Comment by mcervar** [comment]
ohhh, you are right, my bad, I thought filter was applied but somehow that log message was caught by it.
still nothing what can point out the problem in the logs, but I noticed that last 4 days it always stops working around 1am, earliest 00:58 am, latest around 01:03 am. I already checked my automations and nothing is triggered at that time.

Does integration maybe trigger something at that time? Also worth to mention, energy metrics stopped working with this new update. Maybe it tries to fetch energy metrics around 1am and something goes wrong there XD

**Comment by pszafer** [comment]
Can you try to turn on debug log of the integration and library in the evening and provide what is happening in the night.
As it's Easycontrol it just download last day at 1am.

**Comment by mcervar** [comment]
I am already running debug mode, attached logs in previous comments

Debug mode set like this:

logger:
  default: warning
  logs:
    custom_components.bosch: debug
    bosch_thermostat_client: debug

**Comment by ChristophPech** [comment]
I do have the same issue since the last update. The debug log doesn't show anything out of the ordinary, the regular "Update of climate ... component called." still continue normally but all the values stop updating until I reload the integration. It happens at 4 o'clock every night, which is the same time my internet router reconnects and receives a new public IPv4.

**Comment by mcervar** [comment]
My IP doesnt change at problematic time of the integration, only clue is this in the logs which starts showing after integration stops working properly:

2024-04-28 01:02:01.712 DEBUG (MainThread) [custom_components.bosch] Update already in progress. Not updating.

@ChristophPech  can you check if the same occurs in your logs only after integration stops working? You need to enable debug logs if you havent already :D

**Comment by pszafer** [comment]
I think new library doesn't reconnect properly. I'll fix that but HA changed too much in 2024.5; I have to rewrite a lot of code of component and don't have time for that.

**Comment by sergioras** [comment]
I have the same issue. 
I temporarily solved it with an automation that reloads the integration every 24h:
service: homeassistant.reload_config_entry
target: {}
data:
  entry_id: 06d7ca863dc3f075184f663ef0399e10

I found the correct entry_id in the core.config_entries file.

**Comment by ChristophPech** [comment]
> I found the correct entry_id in the core.config_entries file.

You can find the ID in the URL when listing devices of the bosch integration: 
![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/3427525/6584e965-02d6-462f-80f8-4e83f4766bc4)

**Comment by sergioras** [comment]
Great suggestion!
Thanks

Sergio

Il mer 29 mag 2024, 11:23 Christoph Pech ***@***.***> ha
scritto:

**Comment by andyktaylor** [comment]
> I have the same issue. I temporarily solved it with an automation that reloads the integration every 24h: service: homeassistant.reload_config_entry target: {} data: entry_id: 06d7ca863dc3f075184f663ef0399e10
> 
> I found the correct entry_id in the core.config_entries file.

Been wondering why this suddenly stops working for a while now. Your solution works a treat, thanks!

**Comment by CR6-SE** [comment]
I have the same problem. 
Can you explain me how to set up the Automation correctly?

Best regards

**Comment by Novae7** [comment]
just as an information.

i found that the integration stops working when my external IP changes, so when my internet is down for a short period everything stops working
then a reload fixes this

so it looks like the integration doesnt recognize when the connection drops

**Comment by JackPoint** [comment]
This is probably related to #473

**Comment by prj** [comment]
This is still a problem.

In my case every time the internet connection gets dropped for any reason (e.g. wifi drops on home assistant box), then the integration stops working...

Integration is pretty much unusable with this issue.
