### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by moritzmaier84** [bosch-thermostat/home-assistant-bosch-custom-component#428]
This one is showing up all day.

Logger: homeassistant
Quelle: custom_components/bosch_shc/switch.py:458
Integration: Bosch SHC ([Dokumentation](https://github.com/tschamm/boschshc-hass/blob/master/README.md), [Probleme](https://github.com/tschamm/boschshc-hass/issues))
Erstmals aufgetreten: 09:38:31 (17 Vorkommnisse)
Zuletzt protokolliert: 09:46:30

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1050, in _async_update_entity_states
    await entity.async_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 959, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1126, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1061, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1661, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/bosch_shc/switch.py", line 458, in is_on
    getattr(self._device, self.entity_description.on_key)
  File "/usr/local/lib/python3.12/site-packages/boschshcpy/models_impl.py", line 452, in cameranotification
    return self._cameranotification_service.value
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by slovdahl** [comment]
> Integration: Bosch SHC ([Dokumentation](https://github.com/tschamm/boschshc-hass/blob/master/README.md), [Probleme](https://github.com/tschamm/boschshc-hass/issues))

Wrong custom integration, file an issue in https://github.com/tschamm/boschshc-hass instead.
