### ISSUE TITLE
Component does not load on HA 2024.8

### ISSUE THREAD

**Issue by rikroe** [bosch-thermostat/home-assistant-bosch-custom-component#429]
### > See comment below.

**Describe the bug**
Currently running HA 2024.8 beta and getting this error message on startup:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/bosch/__init__.py", line 50, in <module>
    from homeassistant.util.json import load_json, save_json
ImportError: cannot import name 'save_json' from 'homeassistant.util.json' (/usr/src/homeassistant/homeassistant/util/json.py)
```

Issue is in this cleanup pull request: https://github.com/home-assistant/core/pull/121069

**To Reproduce**
1. Install this component on HA 2024.8 beta or later.

**Expected behavior**
Integration loaded.

**Version**
  - HA version >= 2024.8.0b0
  - HA Bosch component version? v0.25.2
  - Python Bosch HTTP client version? N/A

**Additional context**
Will create a PR to fix it, but wanted to mention it as issue for others to find.

**Comment by rikroe** [comment]
Nevermind, just realized it was already fixed by @slovdahl in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/pull/427.

However it would be great it a new release can be cut before 2024-08-07 when HA 2024.8 get released.

**Comment by fisch55** [comment]
change the two line in init.py.... it will works like before and the integration starts...

**Comment by rikroe** [comment]
Yep, but a release before would be great, otherwise many people will come here.

**Comment by rikroe** [comment]
Closes by https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.26.1.
