### ISSUE TITLE
HA 2024.10.0b6 - Setup failed for custom integration 'bosch'

### ISSUE THREAD

**Issue by gralin** [bosch-thermostat/home-assistant-bosch-custom-component#446]
**Describe the bug**

There are some breaking changes in HA 2024.10 which prevent this integration from starting. 

```Unable to import component: cannot import name 'process_datetime_to_timestamp' from 'homeassistant.components.recorder.models'```

**To Reproduce**

Update HA to 2024.10.0b6

**Version**
  - HA 2024.10.0b6
  - HA Bosch component v0.26.2

**Additional context**

```
Logger: homeassistant.setup
Source: setup.py:334
First occurred: 09:55:17 (1 occurrences)
Last logged: 09:55:17

Setup failed for custom integration 'bosch': Unable to import component: cannot import name 'process_datetime_to_timestamp' from 'homeassistant.components.recorder.models' (/usr/src/homeassistant/homeassistant/components/recorder/models/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/bosch/__init__.py", line 86, in <module>
    from .services import (
  File "/config/custom_components/bosch/services.py", line 24, in <module>
    from .sensor.recording import RecordingSensor
  File "/config/custom_components/bosch/sensor/__init__.py", line 17, in <module>
    from .energy import EcusRecordingSensors, EnergySensor, EnergySensors
  File "/config/custom_components/bosch/sensor/energy.py", line 6, in <module>
    from .statistic_helper import StatisticHelper
  File "/config/custom_components/bosch/sensor/statistic_helper.py", line 7, in <module>
    from homeassistant.components.recorder.models import (
ImportError: cannot import name 'process_datetime_to_timestamp' from 'homeassistant.components.recorder.models' (/usr/src/homeassistant/homeassistant/components/recorder/models/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/bosch/__init__.py", line 86, in <module>
    from .services import (
  File "/config/custom_components/bosch/services.py", line 24, in <module>
    from .sensor.recording import RecordingSensor
  File "/config/custom_components/bosch/sensor/__init__.py", line 17, in <module>
    from .energy import EcusRecordingSensors, EnergySensor, EnergySensors
  File "/config/custom_components/bosch/sensor/energy.py", line 6, in <module>
    from .statistic_helper import StatisticHelper
  File "/config/custom_components/bosch/sensor/statistic_helper.py", line 7, in <module>
    from homeassistant.components.recorder.models import (
ImportError: cannot import name 'process_datetime_to_timestamp' from 'homeassistant.components.recorder.models' (/usr/src/homeassistant/homeassistant/components/recorder/models/__init__.py)
```

**Comment by fisch55** [comment]
Same here ….

**Comment by gralin** [comment]
New version v0.26.3 was released which should fix this issue. I will test it once official HA 2024.10 is released

**Comment by HansDoeve** [comment]
@gralin : Does not work with my HA

Re-load, HA-restart, System restart does not help.

Home Assistent:
Core 2024.10.0
Supervisor 2024.09.1
Operating System 
Frontend 20241002.2

Host:
Operating system	Ubuntu Linux 22.04.5
Time on system	Thursday, October 3, 2024 3:15 PM	
Kernel and CPU	Linux 4.9.337-38 on aarch64
Processor information	Hardkernel ODROID-N2Plus, 6 cores

Log details:
Logger: homeassistant.setup
Bron: setup.py:334
Eerst voorgekomen: 15:04:51 (1 gebeurtenissen)
Laatst gelogd: 15:04:51

Setup failed for custom integration 'bosch': Unable to import component: No module named 'custom_components.bosch.sensor.const'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/bosch/__init__.py", line 86, in <module>
    from .services import (
  File "/config/custom_components/bosch/services.py", line 24, in <module>
    from .sensor.recording import RecordingSensor
  File "/config/custom_components/bosch/sensor/__init__.py", line 57, in <module>
    from .const import (
ModuleNotFoundError: No module named 'custom_components.bosch.sensor.const'
![HA-Bosch-integration](https://github.com/user-attachments/assets/f4660559-2863-451a-87f9-a936b4457b61)

**Comment by Novae7** [comment]
i have the same issue :-(
Updated HA and then the Integration

**Comment by fisch55** [comment]
Here it works!

**Comment by Novae7** [comment]
> i have the same issue :-( Updated HA and then the Integration

whatever happened, i restarted my HA today again because some of the notifications about old entries didnt disappear

after that everything went back to normal?!

Maybe there is a backgroundtask after updating which needs to complete bevore the integration can be loaded again?

**Comment by HansDoeve** [comment]
Latest fix does the trick, looks like working OK.
Updated the custom component files again (some changes reverted ??!) and restarted HA.

**Comment by gralin** [comment]
Works for me too. Using HA 2024.10.1 and bosch-thermostat v0.26.3
