### ISSUE TITLE
Fehler/Warnung im Protokoll

### ISSUE THREAD

**Issue by IOGogo** [bosch-thermostat/home-assistant-bosch-custom-component#448]
Ich bekomme ständig im Protokoll Warnungen und Fehlermeldungen.

Der Fehler ist für mich nich reproduzierbar.

Homeassistant > Version core_2024.10.1
Bosch Thermostat > 0.26.3  ( RC300/RC310 netfit Muduline 3000)

Logger: homeassistant.helpers.entity
Quelle: helpers/entity.py:942
Erstmals aufgetreten: 06:54:24 (550 Vorkommnisse)
Zuletzt protokolliert: 09:11:25

Update for sensor.switch_temp fails
Update for sensor.chimney_temp fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/config/custom_components/bosch/sensor/base.py", line 118, in async_update
    if self._attr_state_class
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BoschSensor' object has no attribute '__attr_state_class'. Did you mean: '_attr_state_class'?

**Comment by davidhrbac** [comment]
Same here. I need to reboot HA almost every day.

```console
2024-10-21 21:08:06.863 WARNING (MainThread) [bosch_thermostat_client.sensors.sensor] Can't update data for System pressure. Trying uri: /heatSources/systemPressure. Error message: URI /heatSources/systemPressure doesn not exist: 404, message='Not Found', url='http://192.168.88.147/heatSources/systemPressure'
2024-10-21 21:08:08.578 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'bosch_sensor_update': ()
Traceback (most recent call last):
File "/config/custom_components/bosch/sensor/base.py", line 118, in async_update
if self._attr_state_class
^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BoschSensor' object has no attribute '__attr_state_class'. Did you mean: '_attr_state_class'?
2024-10-21 21:08:30.302 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.system_pressure fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
await self.async_update()
File "/config/custom_components/bosch/sensor/base.py", line 118, in async_update
if self._attr_state_class
^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BoschSensor' object has no attribute '__attr_state_class'. Did you mean: '_attr_state_class'?
```
