### ISSUE TITLE
CT 200 not working

### ISSUE THREAD

**Issue by CR6-SE** [bosch-thermostat/home-assistant-bosch-custom-component#449]
**Describe the bug**
CT 200 stops working after a specific time. To solve the Problem you have to restart Homeassistant every time.

**To Reproduce**
No actions needed. Just stops working after a wile. Seems to be no communication between CT200 and Homeassistant.

**Expected behavior**

**Screenshots**

Got some Errors:
Logger: slixmpp.stringprep
Quelle: custom_components/bosch/__init__.py:14
Integration: Bosch thermostat (Dokumentation, Probleme)
Erstmals aufgetreten: 09:54:03 (1 Vorkommnisse)
Zuletzt protokolliert: 09:54:03

Using slower stringprep, consider compiling the faster cython/libidn one.

______________________________________________________________________________________________________________________________________________
Logger: homeassistant.util.loop
Quelle: util/loop.py:136
Erstmals aufgetreten: 09:54:03 (1 Vorkommnisse)
Zuletzt protokolliert: 09:54:03

Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7fbe27ef5e50>, <Purpose.SERVER_AUTH: _ASN1Object(nid=129, shortname='serverAuth', longname='TLS Web Server Authentication', oid='1.3.6.1.5.5.7.3.1')>) inside the event loop by custom integration 'bosch' at custom_components/bosch/__init__.py, line 234: self.gateway = BoschGateway( (offender: /usr/local/lib/python3.12/ssl.py, line 713: context.load_default_certs(purpose)), please create a bug report at https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component await asyncio.gather( File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/bosch/__init__.py", line 151, in async_setup_entry _init_status: bool = await gateway_entry.async_init() File "/config/custom_components/bosch/__init__.py", line 234, in async_init self.gateway = BoschGateway(

______________________________________________________________________________________________________________________________________________

Logger: homeassistant.util.loop
Quelle: util/loop.py:77
Erstmals aufgetreten: 09:54:04 (1 Vorkommnisse)
Zuletzt protokolliert: 09:54:04

Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7fbe27ef5e50>,) in /usr/local/lib/python3.12/site-packages/slixmpp/xmlstream/xmlstream.py, line 813: self.ssl_context.load_verify_locations(cafile=ca_cert) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/slixmpp/xmlstream/handler/coroutine_callback.py", line 60, in pointer_wrapper await pointer(stanza) File "/usr/local/lib/python3.12/site-packages/slixmpp/features/feature_starttls/starttls.py", line 63, in _handle_starttls_proceed if await self.xmpp.start_tls(): File "/usr/local/lib/python3.12/site-packages/slixmpp/xmlstream/xmlstream.py", line 828, in start_tls ssl_context = self.get_ssl_context() File "/usr/local/lib/python3.12/site-packages/slixmpp/xmlstream/xmlstream.py", line 813, in get_ssl_context self.ssl_context.load_verify_locations(cafile=ca_cert)

______________________________________________________________________________________________________________________________________________

** Debug SCAN **
**http://jsonblob.com/1296393173562417152**

Best Regards

**Comment by CR6-SE** [comment]
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.bosch
Quelle: custom_components/bosch/__init__.py:418
Integration: Bosch thermostat (Dokumentation, Probleme)
Erstmals aufgetreten: 03:41:54 (1564 Vorkommnisse)
Zuletzt protokolliert: 10:12:22

Bosch object of entity Lia is no longer available. Error requesting data from /programs/list
Bosch object of entity Lars is no longer available. Error requesting data from /programs/list
Bosch object of entity Schlafzimmer is no longer available. Error requesting data from /programs/list
Bosch object of entity Arbeitszimmer is no longer available. Error requesting data from /programs/list
Bosch object of entity Keller is no longer available. Error requesting data from /programs/list

**Comment by mmakaay** [comment]
Possibly a duplicate of #454

**Comment by omerfaruk-aran** [comment]
If you see the following warning in the logs:

```
Using slower stringprep, consider compiling the faster cython/libidn one.
```

You can suppress this warning by adding the following line to your `configuration.yaml` file:

```yaml
logger:
  logs:
    slixmpp.stringprep: error
```

This will hide warnings from the `slixmpp.stringprep` module and keep your logs clean. It does not affect performance or functionality.
