### ISSUE TITLE
V 0.9.11 installation Bosch KM200 no entities

### ISSUE THREAD

**Issue by tempo3** [bosch-thermostat/home-assistant-bosch-custom-component#49]
After new installation via "IVT => HTTP" only the "RC300/RC310/Nefit Moduline 3000" with one device but w/o any entities ist there. 

Home Assistant 2020.12.2, Bosch thermostat V 0.9.11

I've also tested to install via NEFIT(XMPP only). => Unknown error occurred

and 

IVT => XMPP => Unknown error occurred

[bosch_scan_2021.01.02.pdf](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/5760815/bosch_scan_2021.01.02.pdf)

**Comment by pszafer** [comment]
Check logs.

I can't reproduce testing out your json bosch_scan.
![image](https://user-images.githubusercontent.com/690510/103482231-f6e23e00-4ddf-11eb-823f-8ed7005a75a6.png)

![image](https://user-images.githubusercontent.com/690510/103482248-18432a00-4de0-11eb-90cf-f65b558bc96b.png)

Check out if you have such info in your logs:
```
2021-01-03 16:22:22 DEBUG (MainThread) [bosch_thermostat_client.gateway.ivt_gateway] Found supported device {'value': 'RC300', 'name': 'RC300/RC310/Nefit Moduline 3000', 'type': 'RC300'} with
 id 158                                                                                                                                                                                        
2021-01-03 16:22:22 DEBUG (MainThread) [bosch_thermostat_client.gateway.ivt_gateway] Using model RC300 as database schema                         
2021-01-03 16:22:22 DEBUG (MainThread) [bosch_thermostat_client.db] Attempt to load database from file /.../core/venv/lib/python3.9/site-packages/bosch_thermostat_client/db/rc300.json                                                                                                                                                           
2021-01-03 16:22:22 DEBUG (MainThread) [bosch_thermostat_client.gateway.base_gateway] Loading database: RC300                                                                                  2021-01-03 16:22:22 DEBUG (MainThread) [custom_components.bosch] Bosch BUS detected: EMS                      
```

**Comment by tempo3** [comment]
I dont know whats necessary to do. There is nothing.
![Image](https://user-images.githubusercontent.com/63743500/103488403-738b1180-4e0c-11eb-935c-3ea2ec9e2478.png)

**Comment by pszafer** [comment]
turn on debug logs and paste all lines with 'bosch' in it

**Comment by tomasko25** [comment]
Hello,
I have the same problem. It started after upgrade core to release 2020.12.1. All Bosch CC entities were unavailable so I tried to "reinstall" Bosch CC but after installation, there are no heating circuits, water heater or solar heater devices - as in the @tempo3's picture. Here is part of log after installation:

2021-01-04 11:49:48 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [1753427920] Received {'type': 'frontend/get_translations', 'language': 'sk', 'category': 'config', 'integration': 'bosch', 'id': 32}                                                                                     
2021-01-04 11:49:48 DEBUG (MainThread[homeassistant.components.websocket_api.http.connection] [1753427920] Sending {'id': 32, 'type': 'result', 'success': True, 'result': {'resources': {'component.bosch.config.title': 'Bosch thermostat', 'component.bosch.config.step.choose_type.title': 'Choose device type.', 'component.bosch.config.step.choose_type.data.device_type': 'Choose type of your device.', 'component.bosch.config.step.http_config.title': 'Bosch thermostat HTTP config', 'component.bosch.config.step.http_config.data.address': 'IP address', 'component.bosch.config.step.http_config.data.access_token': 'Access token', 'component.bosch.config.step.http_config.data.password': 'Password', 'component.bosch.config.step.xmpp_config.title': 'Bosch thermostat XMPP config', 'component.bosch.config.step.xmpp_config.data.address': 'Serial number of device', 'component.bosch.config.step.xmpp_config.data.access_token': 'Access token', 'component.bosch.config.step.xmpp_config.data.password': 'Password', 'component.bosch.config.step.protocol.title': 'Bosch IVT Protocol. HTTP is local. XMPP is cloud!', 'component.bosch.config.step.protocol.data.Protocol': 'Either http or xmpp', 'component.bosch.config.error.service_unavailable': 'No service available', 'component.bosch.config.abort.faulty_credentials': 'Bad user credentials or wrong IP', 'component.bosch.config.abort.already_configured': 'Controller site is already configured', 'component.bosch.config.abort.unknown': 'Unknown reason. Check LOGS.'}}}                          2021-01-04 11:50:16 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /gateway/uuid                                         
2021-01-04 11:50:16 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /system/bus                                           
2021-01-04 11:50:16 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /gateway/versionFirmware                              
2021-01-04 11:50:16 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /system/brand                                         
2021-01-04 11:50:16 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /system/info                                          
2021-01-04 11:50:17 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /system/systemType                                    
2021-01-04 11:50:17 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /gateway/DateTime                                     
2021-01-04 11:50:17 DEBUG (MainThread) [custom_components.bosch.config_flow] Adding entry.                                                                    
2021-01-04 11:50:17 INFO (MainThread) [homeassistant.setup] Setting up bosch                                                                                  
2021-01-04 11:50:17 INFO (MainThread) [homeassistant.setup] Setup of domain bosch took 0.0 seconds                                                            
2021-01-04 11:50:17 INFO (MainThread) [custom_components.bosch] Setting up Bosch component version 0.9.2.                                                     
2021-01-04 11:50:17 DEBUG (MainThread) [custom_components.bosch] Checking connection to Bosch gateway as 192.168.1.11.                                        
2021-01-04 11:50:17 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /gateway/uuid                                         
2021-01-04 11:50:17 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /system/bus                                           
2021-01-04 11:50:17 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /gateway/versionFirmware                              
2021-01-04 11:50:17 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /system/brand                                         
2021-01-04 11:50:18 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /system/info                                          
2021-01-04 11:50:18 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /system/systemType                                    
2021-01-04 11:50:18 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /gateway/DateTime                                     
2021-01-04 11:50:18 DEBUG (MainThread) [custom_components.bosch] Bosch BUS detected: EMS                                                                      
2021-01-04 11:50:18 DEBUG (MainThread) [homeassistant.util.json] JSON file not found: /config/custom_bosch_db.json                                            
2021-01-04 11:50:18 INFO (MainThread) [custom_components.bosch] Bosch initialized.                                                                            
2021-01-04 11:50:18 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event service_registered[L]: domain=bosch, service=debug_scan>                      
2021-01-04 11:50:18 DEBUG (MainThread) [custom_components.bosch] Bosch component registered with platforms [].                                                
2021-01-04 11:50:18 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [1753427920] Sending {"id": 7, "type": "event", "event": {"event_type": "service_registered", "data": {"domain": "bosch", "service": "debug_scan"}, "origin": "LOCAL", "time_fired": "2021-01-04T10:50:18.540040+00:00", "context": {"id": "4a2bc05f64e23a23db8636eca1749060", "parent_id": null, "user_id": null}}}                                                                      
2021-01-04 11:50:18 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [1798905784] Sending {"id": 20, "type": "event", "event": {"event_type": "service_registered", "data": {"domain": "bosch", "service": "debug_scan"}, "origin": "LOCAL", "time_fired": "2021-01-04T10:50:18.540040+00:00", "context": {"id": "4a2bc05f64e23a23db8636eca1749060", "parent_id": null, "user_id": null}}}                                                                     
2021-01-04 11:50:18 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event component_loaded[L]: component=bosch>                                         
2021-01-04 11:50:18 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [1798905784] Sending {"id": 18, "type": "event", "event": {"event_type": "component_loaded", "data": {"component": "bosch"}, "origin": "LOCAL", "time_fired": "2021-01-04T10:50:18.548520+00:00", "context": {"id": "668bfa0c175448dc1dfda6bb1492acd0", "parent_id": null, "user_id": null}}}                                                                                             
2021-01-04 11:50:18 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [1798905784] Sending {"id": 24, "type": "event", "event": {"event_type": "component_loaded", "data": {"component": "bosch"}, "origin": "LOCAL", "time_fired": "2021-01-04T10:50:18.548520+00:00", "context": {"id": "668bfa0c175448dc1dfda6bb1492acd0", "parent_id": null, "user_id": null}}}                                                                                             
2021-01-04 11:50:18 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [1753427920] Sending {"id": 4, "type": "event", "event": {"event_type": "component_loaded", "data": {"component": "bosch"}, "origin": "LOCAL", "time_fired": "2021-01-04T10:50:18.548520+00:00", "context": {"id": "668bfa0c175448dc1dfda6bb1492acd0", "parent_id": null, "user_id": null}}}                                                                                              
2021-01-04 11:50:18 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [1753427920] Sending {"id": 17, "type": "event", "event": {"event_type": "component_loaded", "data": {"component": "bosch"}, "origin": "LOCAL", "time_fired": "2021-01-04T10:50:18.548520+00:00", "context": {"id": "668bfa0c175448dc1dfda6bb1492acd0", "parent_id": null, "user_id": null}}} 

I am runnig HA on R-Pi 3b+ and have Buderus web-gate Logamatic KM200.

**Comment by pszafer** [comment]
@tomasko25 you're using v0.9.2. Probably firmware've been updated in December so upgrade component and I guess it should work.

**Comment by tomasko25** [comment]
I did't realize I installed not lastest version. Now it is working. Thank you @pszafer!

**Comment by tempo3** [comment]
@pszafer Thanks a lot in advance. I have now deleted the integration again, including  renaming the folder custom_components/bosch in bosch-xxx before installed again. Everything is as before, but now it works. 

The last open point is this error message:

Logger: homeassistant.helpers.integration_platform
Source: loader.py:429
First occurred: 17:17:57 (4 occurrences)
Last logged: 17:17:57

Unexpected error importing bosch/group.py
Unexpected error importing bosch/system_health.py
Unexpected error importing bosch/logbook.py
Unexpected error importing bosch/media_source.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 30, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 424, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 429, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.bosch-xxx.group'

**Comment by pszafer** [comment]
I don't know what you did, but seems that you renamed wrong folder.
media_source, logbook, system_health etc -> all those are internal Home Assistant modules, there is nothing in my lib like this.

**Comment by tempo3** [comment]
Thanks a lot again for this terrific integration of the Bosch/Buderus device.
