### ISSUE TITLE
CT100 raise NotImplementedError

### ISSUE THREAD

**Issue by marcomsousa** [bosch-thermostat/home-assistant-bosch-custom-component#58]
**Describe the bug**
An error is show in the core logs every minute:

```
Logger: homeassistant
Source: custom_components/bosch/__init__.py:286
First occurred: 22:06:34 (2 occurrences)
Last logged: 22:07:04

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/bosch/__init__.py", line 308, in thermostat_refresh
    await self.component_update(CLIMATE, event_time)
  File "/config/custom_components/bosch/__init__.py", line 286, in component_update
    await entity.bosch_object.update()
  File "/usr/local/lib/python3.8/site-packages/bosch_thermostat_client/circuits/circuit.py", line 242, in update
    if self.schedule:
  File "/usr/local/lib/python3.8/site-packages/bosch_thermostat_client/circuits/circuit.py", line 88, in schedule
    raise NotImplementedError
NotImplementedError
```

**To Reproduce**
Just confirgure the integration and is the log (Using CT100)

**Expected behavior**
No error

**Version**
  - HA version?
core-2021.2.3
   - HA Bosch component version?
 0.10.0

**Comment by pszafer** [comment]
Fixed in 0.10.1
