### ISSUE TITLE
InvalidStateError with CT200

### ISSUE THREAD

**Issue by Didel** [bosch-thermostat/home-assistant-bosch-custom-component#67]
The following error has been observed by multiple people (including me) trying to connect their CT200 thermostat to HomeAssistant. Initially, it seems to connect and get a valid response from the thermostat, but after a while it stops working with the below error. Restarting HA seems to temporarily resolve the error, but also then it will occur again after a while.

```
Logger: aioxmpp.callbacks
Source: /usr/local/lib/python3.8/site-packages/aioxmpp/callbacks.py:536 
First occurred: 18 april 2021 23:03:42 (1occurrences) 
Last logged: 18 april 2021 23:03:42

listener attached to signal raised
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aioxmpp/callbacks.py", line 534, in fire
    keep = wrapper(args, kwargs)
  File "/usr/local/lib/python3.8/site-packages/aioxmpp/callbacks.py", line 468, in _strong_wrapper
    return not f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/aioxmpp/dispatcher.py", line 287, in _feed
    super()._feed(stanza)
  File "/usr/local/lib/python3.8/site-packages/aioxmpp/dispatcher.py", line 135, in _feed
    cb(stanza)
  File "/usr/local/lib/python3.8/site-packages/bosch_thermostat_client/connectors/xmpp.py", line 158, in main_listener
    listener(body, http_response)
  File "/usr/local/lib/python3.8/site-packages/bosch_thermostat_client/connectors/xmpp.py", line 120, in listener
    future.set_result(recv_body)
asyncio.exceptions.InvalidStateError: invalid state
```

_Originally posted by @Didel in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues/64#issuecomment-822214129_

**Comment by pszafer** [comment]
I need debug logs with messages just before this error occured.

**Comment by Lipek1991** [comment]
I have problem:
Logger: custom_components.bosch
Source: custom_components/bosch/__init__.py:241
Integration: Bosch thermostat (documentation, issues)
First occurred: 19:49:14 (1 occurrences)
Last logged: 19:49:14

Cannot connect to Bosch gateway, host xxxxxxxx <my serial with UUID: None

Please help

**Comment by Lipek1991** [comment]
> 
> 
> I have problem:
> Logger: custom_components.bosch
> Source: custom_components/bosch/**init**.py:241
> Integration: Bosch thermostat (documentation, issues)
> First occurred: 19:49:14 (1 occurrences)
> Last logged: 19:49:14
> 
> Cannot connect to Bosch gateway, host xxxxxxxx <my serial with UUID: None
> 
> Please help

Logger: bosch_thermostat_client.gateway.easycontrol_gateway
Source: /usr/local/lib/python3.8/site-packages/bosch_thermostat_client/gateway/easycontrol_gateway.py:100
First occurred: 19:49:13 (2 occurrences)
Last logged: 19:49:14

Couldn't find device model. Got product ID: None

Logger: bosch_thermostat_client.encryption.base_encryption
Source: /usr/local/lib/python3.8/site-packages/bosch_thermostat_client/encryption/base_encryption.py:77
First occurred: 19:49:12 (10 occurrences)
Last logged: 19:49:14

Unable to decrypt: b'\xb2\x84\xb6P\x89r\x8fM\xe8\x12\r\xb8\xb4\x00p@\xc8\xff\x1f\x11\xbd\xa9t\xc3\xf8^\xe5gB\xd1\xcc\x8emW\xd7\x03f\xf5!\x19\xea\xdc\x05\xcf\xb7R`9\xa79\x04\x12@,\xce\xed\xd2\x9e\xd6\x00-\x85\x1cO\xa2\xc9\xd4\x7f7|E\xce\xef\xdf{-\x07{\x8de,\xdbV+\xb8W\x1b\xb5\x0b\xd7\x9f\xc2{\x0fh\xdd' with error: 'utf-8' codec can't decode byte 0xb2 in position 0: invalid start byte
Unable to decrypt: b'\x85lP\x8a\x80\xf9Krng\xcf\xf2\x8d\xf3\x9bbS]Y\xe8x\xd2\xab\xd5}#\x882\xc5\xd9\xecT\x8b\x02\xf4\xac\xf9\xba\x11\x81\xa3\x82Ll\x98\x9fer\x803\xb6F\xda\xce(\x0c\x1aKrAa\x03\xba\x01K\xfd\xf0\xbaq\x9642\xd7\x04\xc9\xe8)\xfb\x7f\x8aT~a\x88|I9Y\xfao\r\xed\x94Z\xfb+\xfe\x82H\x80w\xc8\xe1\xa6\xfan\x82Ay]j\xe0' with error: 'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte
Unable to decrypt: b'\x85lP\x8a\x80\xf9Krng\xcf\xf2\x8d\xf3\x9bb\n&|d\xb7)0Z>^\\\xe18\xdc/J\xac\xee5r0\x1e\x08\xd7\xd0V\xe2\x1cm\x1a\xb9\xf7\xef\xf7\xc2O\xc7\x0f7\xa9\xa2U3\xa3\x12\xf8\xa2\xe9\xc9s\xc6\x1a\xdf\xba\x1dA&\xfb\xd1\x13\xaa\xebK\x9fM\xfe\xe1\xa4\xc0wz2\x0b\xc2\xc3\xde(\xda\n\xc5\x0f\x8d2xf\xed\x00\t\x9a>Q}{\xff\x1c#' with error: 'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte
Unable to decrypt: b'\x85lP\x8a\x80\xf9Krng\xcf\xf2\x8d\xf3\x9bbH_f.G\xedK\xcd\x8e2\x80j\t%{\xf5\xb1uTm\xfd<\xd0\xeb\x8e=\xdc\x7f\x01\x8fE\'\xd7\x01\x90H\x84\x83Sy\xe7\xf5er\xb4\xd7)\x13\xff\xca\xc32\x0b\x86\xe7\xe2\x9cJ\x9b-bj\xdc\t\xa1V"@y\xe2#\xe8j2Ow\xf7\xfe\xcbx\xc4\xef\x89\x9b\x8e}\x8c\x1e0[\x86?\xe2\x06\x11\xdf\xab\x89\xa3\xcd!\x98lDM\x0e\xacDjr\x97I' with error: 'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte
Unable to decrypt: b'\x85lP\x8a\x80\xf9Krng\xcf\xf2\x8d\xf3\x9bbH_f.G\xedK\xcd\x8e2\x80j\t%{\xf5\xb1uTm\xfd<\xd0\xeb\x8e=\xdc\x7f\x01\x8fE\'\xd7\x01\x90H\x84\x83Sy\xe7\xf5er\xb4\xd7)\x13\xff\xca\xc32\x0b\x86\xe7\xe2\x9cJ\x9b-bj\xdc\t\xa1V"@y\xe2#\xe8j2Ow\xf7\xfe\xcbxe\xb68\xd0\x7f\xaa\xea\xfe_O7\x8aN\x19\x17\xdc\xab\x89\xa3\xcd!\x98lDM\x0e\xacDjr\x97I' with error: 'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte

**Comment by pszafer** [comment]
@Lipek1991  open new issue.

**Comment by pszafer** [comment]
@Didel can you check current master if it is better?

**Comment by Didel** [comment]
> @Didel can you check current master if it is better?

@pszafer yes, it looks like the current master doesn’t show the error any more and it has been working all night now. So I’d say the current master fixes this problem!

**Comment by pszafer** [comment]
Let's wait at least one day to make sure if it's not coincidence

**Comment by Didel** [comment]
@pszafer I'm not sure if it is related, or if it is a different issue on its own. But I am seeing one interesting recurring error (which is reported as 'info' in the logging), which might explain an invalid state:

```
2021-04-24 23:58:55 DEBUG (MainThread) [custom_components.bosch] Updating component water_heater by 548401686992
2021-04-24 23:58:55 DEBUG (MainThread) [bosch_thermostat_client.circuits.circuit] Updating circuit dhw1
2021-04-24 23:58:55 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Sending GET request to /dhwCircuits/dhw1/actualTemp by 548381828384
2021-04-24 23:58:55 DEBUG (SyncWorker_11) [custom_components.bosch.climate] Update of climate Woonkamer component called.
2021-04-24 23:58:55 DEBUG (SyncWorker_11) [bosch_thermostat_client.circuits.circuit] Current temp of WOONKAMER is {'value': 21.5, 'minValue': 5.0, 'maxValue': 30.0, 'unitOfMeasure': 'C', 'writeable': 0, 'used': 'true'}
2021-04-24 23:58:55 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.1 404 Not Found', 'Seq-No: 0', 'Content-Length: 0', 'Content-Type: application/json', 'Connection: close', '', '']
2021-04-24 23:58:55 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /dhwCircuits/dhw1/actualTemp
2021-04-24 23:58:55 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Sending GET request to /dhwCircuits/dhw1/operationMode by 548381828384
2021-04-24 23:58:55 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Sending GET request to /dhwCircuits/dhw1/temperatureLevels/high by 548381828384
2021-04-24 23:58:55 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Sending GET request to /dhwCircuits/dhw1/state by 548381828384
2021-04-24 23:58:55 DEBUG (MainThread) [bosch_thermostat_client.connectors.xmpp] Sending GET request to /dhwCircuits/dhw1/programs by 548381828384
2021-04-24 23:58:56 DEBUG (MainThread) [custom_components.bosch] Bosch water_heater entitites updated.
2021-04-24 23:58:56 DEBUG (SyncWorker_6) [custom_components.bosch.water_heater] Updating Bosch water_heater.
2021-04-24 23:58:56 DEBUG (SyncWorker_6) [bosch_thermostat_client.circuits.circuit] Current temp of DHW1 is {}
```

**Comment by pszafer** [comment]
Actual temp won't be fetched in new version (will be released in a few days). Closing it for now.
