### ISSUE TITLE
AttributeError for CT200

### ISSUE THREAD

**Issue by Didel** [bosch-thermostat/home-assistant-bosch-custom-component#69]
**Describe the bug**
In the latest master (c74e750), I see several occurrences of the following message appearing in the Home assistant logs:

```
Logger: homeassistant
Source: custom_components/bosch/__init__.py:377
First occurred: 4:11:45 (5 occurrences) 
Last logged: 20:11:46

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/bosch/__init__.py", line 377, in firmware_refresh
    await self.gateway.check_firmware_validity()
  File "/usr/local/lib/python3.8/site-packages/bosch_thermostat_client/gateway/base_gateway.py", line 299, in check_firmware_validity
    self._db = get_db_of_firmware(self._device[TYPE], fw)
  File "/usr/local/lib/python3.8/site-packages/bosch_thermostat_client/db/__init__.py", line 41, in get_db_of_firmware
    filename = DEVICE_TYPES[device_type].format(firmware_version.replace(".", ""))
AttributeError: 'dict' object has no attribute 'replace'
```

**Version**
  - HA version: 2021.4.6
  - HA Bosch component version: Master, commit c74e750

**Comment by pszafer** [comment]
Fixed in latest master: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/commit/aeccca54cd411bb1be2dea48f82e1209a688e284

Let me know if problem still occurs, then we can reopen.
