### ISSUE TITLE
Firmware: 04.07.07

### ISSUE THREAD

**Issue by ropperto** [bosch-thermostat/home-assistant-bosch-custom-component#81]
[bosch_scan.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/6968914/bosch_scan.zip)
Hello, bosh installed new release 04.07.07 on the gateway and it is not yet supported.
Scan is attached.

**Comment by ropperto** [comment]
Not sure but I think is a KM300, how can I verify?

**Comment by slovdahl** [comment]
Same here, IVT and this entry in the `db_IVT.json` file:

```json
    "172": {
      "value": "iCom_Low_NSC_v1",
      "name": "Enviline/Compress 6000/7000",
      "type": "NSC_ICOM_GATEWAY"
    },
```
Log from HASS: https://paste.ubuntu.com/p/yT2sdT4HsN/

**Comment by slovdahl** [comment]
[rawscan_957421505.json.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/6970358/rawscan_957421505.json.zip)

**Comment by tomasko25** [comment]
After update, still not working:
![image](https://user-images.githubusercontent.com/72974725/129169865-d98131e0-dbb2-4bcc-b77e-e950283579af.png)

**Comment by pszafer** [comment]
You have different device. I need you bosch scan.

**Comment by luke-g86** [comment]
KM200 is having similar problem. Gateway cannot be even paired

**Comment by pszafer** [comment]
I need one scan from RC300/RC200 device so I can check if they changed something important and then re-add it.

**Comment by luke-g86** [comment]
Unfortunately I am experiencing problems with pairing thus I cannot download data for the service, but...

I see these logs 

Error connecting Bosch at 192.168.1.237 - [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/db/rc300_rc200/040707.json'

and

Logger: aiohttp.server
Source: data_entry_flow.py:273 
First occurred: 11:57:36 (1 occurrences) 
Last logged: 11:57:36

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 84, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 155, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 202, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 273, in _async_handle_step
    if result["type"] not in (
TypeError: 'NoneType' object is not subscriptable

**Comment by luke-g86** [comment]
Alternatively if there's any way to help you, please advise me what to do ;)

**Comment by pszafer** [comment]
https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/wiki/Unsupported-firmware

**Comment by Nemor213** [comment]
[rawscan_None.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/6975484/rawscan_None.zip)

Same here. KM200 with new Firmware 04.07.07.

**Comment by tomasko25** [comment]
> You have different device. I need you bosch scan.

[rawscan_None.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/6975662/rawscan_None.zip)

**Comment by pszafer** [comment]
new version released. Let me know if it is working

**Comment by tomasko25** [comment]
It works flawlessly. Thanks!
