### ISSUE TITLE
Buderus Logomatic TC100 Support

### ISSUE THREAD

**Issue by CreshD** [bosch-thermostat/home-assistant-bosch-custom-component#82]
Request for new device and firmware support

(venv) parallels@upvp:~/bosch$ bosch_cli scan -i --host=1 --token=1 --password=1
[rawscan_None.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/6993783/rawscan_None.txt)
 --protocol=XMPP --device=NEFIT
2021-08-16 18:55:08 INFO (MainThread) [bosch_thermostat_client.bosch_cli] Running scan
2021-08-16 18:55:08 INFO (MainThread) [bosch_thermostat_client.bosch_cli] Successfully connected to gateway. Found UUID: None
2021-08-16 18:55:18 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 403 Forbidden', 'Content-Type: application/json', 'connection: close', '', '']
2021-08-16 18:55:18 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/installerpassword
2021-08-16 18:55:25 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/remote/fdlogger
2021-08-16 18:55:26 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 403 Forbidden', 'Content-Type: application/json', 'connection: close', '', '']
2021-08-16 18:55:26 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/softreset
2021-08-16 18:55:30 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 403 Forbidden', 'Content-Type: application/json', 'connection: close', '', '']
2021-08-16 18:55:30 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/update/request
2021-08-16 18:55:31 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 403 Forbidden', 'Content-Type: application/json', 'connection: close', '', '']
2021-08-16 18:55:31 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/userpassword
2021-08-16 18:55:34 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 403 Forbidden', 'Content-Type: application/json', 'connection: close', '', '']
2021-08-16 18:55:34 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/wifi/update/request
2021-08-16 18:55:41 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 400 Bad Request', 'Content-Type: application/json', 'connection: close', '', '']
2021-08-16 18:55:41 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /heatSources
2021-08-16 18:55:45 ERROR (MainThread) [aioxmpp.callbacks] listener attached to signal raised
Traceback (most recent call last):
  File "/home/parallels/bosch/venv/lib/python3.8/site-packages/bosch_thermostat_client/encryption/base_encryption.py", line 46, in json_encrypt
    return json.loads(self.decrypt(raw), cls=self.jsondecoder)
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 1 column 102 (char 101)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/parallels/bosch/venv/lib/python3.8/site-packages/aioxmpp/callbacks.py", line 534, in fire
    keep = wrapper(args, kwargs)
  File "/home/parallels/bosch/venv/lib/python3.8/site-packages/aioxmpp/callbacks.py", line 468, in _strong_wrapper
    return not f(*args, **kwargs)
  File "/home/parallels/bosch/venv/lib/python3.8/site-packages/aioxmpp/dispatcher.py", line 287, in _feed
    super()._feed(stanza)
  File "/home/parallels/bosch/venv/lib/python3.8/site-packages/aioxmpp/dispatcher.py", line 135, in _feed
    cb(stanza)
  File "/home/parallels/bosch/venv/lib/python3.8/site-packages/bosch_thermostat_client/connectors/xmpp.py", line 173, in main_listener
    body = self._encryption.json_encrypt(body[-1:][0])
  File "/home/parallels/bosch/venv/lib/python3.8/site-packages/bosch_thermostat_client/encryption/base_encryption.py", line 49, in json_encrypt
    raise DeviceException("Unable to decode Json response.")
bosch_thermostat_client.exceptions.DeviceException: Unable to decode Json response.
2021-08-16 18:55:50 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /system/appliance/serialnumber
2021-08-16 18:55:56 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /system/appliance/softreset
2021-08-16 18:56:03 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /system/appliance/systemPressure
2021-08-16 18:56:09 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /system/appliance/type
2021-08-16 18:56:15 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /system/appliance/version
2021-08-16 18:56:21 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /system/interfaces
2021-08-16 18:56:27 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /system/brand
2021-08-16 18:56:33 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /system/location
2021-08-16 18:56:39 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /system/sensors
2021-08-16 18:56:45 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /solarCircuits
2021-08-16 18:56:51 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /recordings
2021-08-16 18:56:57 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /devices
2021-08-16 18:57:03 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /energy
2021-08-16 18:57:09 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /events
2021-08-16 18:57:15 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /programs
2021-08-16 18:57:21 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /zones
2021-08-16 18:57:27 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /ecus
2021-08-16 18:57:27 INFO (MainThread) [bosch_thermostat_client.bosch_cli] Successfully saved result to file: rawscan_None.json

**Comment by pszafer** [comment]
Should work: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.13.2
Note. Your thermostat throws some errors for you. Don't have source what does it mean but maybe it's worth looking.

**Comment by CreshD** [comment]
YEP!!! it work!!!
1) i get 4 devices
2) i get hc1 with set and current temp (looking good)
3) outdoor temp (tc100 get in from cloud) looking good
4) system pressure =25.5 bar, not good =)

ill do better research in a week

THANK YOU SO MUCH!!!

**Comment by pszafer** [comment]
system pressure 25.5 means that your sensor value is invalid (sensor missing, broken etc.)

**Comment by CreshD** [comment]
Hi
Look this logs 
[logs.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7005099/logs.txt)

1. set and current temp update faild (i change set temp from TC100 - in HA it do not change, current temp also do not change in 12hours) manual update from dev tools do not work
2. setting new value of set temp do not work in both operational states
3. setting operation statr from HA work good and fast, but changing it from TC100 doesnt take effect in HA

**Comment by CreshD** [comment]
All working good, now looking for local mode =))
