### ISSUE TITLE
Error setting up entry Bosch EasyControl CT200 for bosch

### ISSUE THREAD

**Issue by arteta22000** [bosch-thermostat/home-assistant-bosch-custom-component#92]
Hello,

Following the upgrade to v0.15.1, I have this error:

`Cette erreur provient d'une intégration personnalisée

Logger: homeassistant.config_entries
Source: custom_components/bosch/__init__.py:274
Integration: Bosch thermostat (documentation, issues)
First occurred: 12:14:42 (1 occurrences)
Last logged: 12:14:42

Error setting up entry Bosch EasyControl CT200 for bosch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/bosch/__init__.py", line 124, in async_setup_entry
    return await gateway_entry.async_init()
  File "/config/custom_components/bosch/__init__.py", line 206, in async_init
    if await self.async_init_bosch():
  File "/config/custom_components/bosch/__init__.py", line 274, in async_init_bosch
    supported_bosch = await self.gateway.get_capabilities()
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/gateway/base.py", line 219, in get_capabilities
    circuit_object = await self.initialize_circuits(circuit)
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/gateway/base.py", line 242, in initialize_circuits
    await self._data[circ_type].initialize(
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/circuits/circuits.py", line 80, in initialize
    circuit_object = self.create_circuit(circuit, database, current_date)
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/circuits/circuits.py", line 90, in create_circuit
    return Circuit(
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/circuits/easycontrol/zone.py", line 21, in __init__
    super().__init__(connector, attr_id, db, _type, bus_type, current_date)
TypeError: __init__() takes 6 positional arguments but 7 were given
`

Any ideas?

**Comment by pfletcher1973** [comment]
i had the same issue on upgrading. I removed the integration and from HACS. Then reinstalled. Same issue

**Comment by pszafer** [comment]
Fixed in 0.15.3
