### ISSUE TITLE
Component does not complete setup on latest HA version

### ISSUE THREAD

**Issue by prj** [bosch-thermostat/home-assistant-bosch-custom-component#96]
Completely clean install of HA, only HACS installed, nothing else.

Component installed via HACS, but can not add the integration.
Always get the following error:
```
Error setting up entry iCom_low_CAN_v1 CAN for bosch

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/bosch/__init__.py", line 124, in async_setup_entry
    return await gateway_entry.async_init()
  File "/config/custom_components/bosch/__init__.py", line 206, in async_init
    if await self.async_init_bosch():
  File "/config/custom_components/bosch/__init__.py", line 274, in async_init_bosch
    supported_bosch = await self.gateway.get_capabilities()
  File "/usr/local/lib/python3.9/site-packages/bosch_thermostat_client/gateway/base.py", line 230, in get_capabilities
    if self._data[SWITCHES].number_switches:
KeyError: 'switches'
```
bosch_cli works perfectly from the command line on my PC.

HA version 2021.10.4, Raspberry Pi 3 with HASS image.

**Comment by prj** [comment]
Same exact error.
Or did you mean I should install older HA version?

**Comment by pszafer** [comment]
v0.16 will work only with 2021.10

**Comment by deric** [comment]
@pszafer Thanks, with update Home Assistant it works fine.
